Die in case of _SKIP_POST_FAIL_HOOKS
os-autoinst/os-autoinst pull request #1528
Opened 2020-09-07 14:55 UTC by asmorodskyi

In previous implementation of _SKIP_POST_FAIL_HOOKS
die was skipped in case of failure. This patch
improve situation so you can use fatal test flag
together with _SKIP_POST_FAIL_HOOKS

2020-09-07 15:01 UTC, SergioAtSUSE approved these changes

2020-09-07 15:37 UTC, Martchus approved these changes

2020-09-08 05:31 UTC, okurz requested changes
Not sure if it is that easy but could be. Please add corresponding test coverage in t/17-basetest.t

2020-09-14 18:42 UTC, okurz commented on t/17-basetest.t
> +use Test::Exception;
please move up to group with the other `Test::…` imports

2020-09-14 18:42 UTC, okurz commented on t/17-basetest.t
> +    $autotest->noop('set_current_test');
as you just use the mock object once you can combine both lines:

```suggestion
    Test::MockModule->new('autotest')->noop('set_current_test');
```

2020-09-14 18:42 UTC, okurz commented on t/17-basetest.t
> +
I suggest to remove this blank line.

2020-09-14 18:42 UTC, okurz commented on t/17-basetest.t
> +
Remove blank lines in between. Also to make the test strings unique and provide the text you have as in-line comment during runtime I suggest the following:

```suggestion
    $bmwqemu::vars{_SKIP_POST_FAIL_HOOKS} = 1;
    dies_ok { $basetest->runtest } 'run_post_fail behavior persists regardless of _SKIP_POST_FAIL_HOOKS setting';
```

2020-09-15 06:27 UTC, asmorodskyi commented
All suggestions applied

2020-09-15 07:25 UTC, okurz approved these changes
Great. Thank you for increasing our test code coverage :)

2020-09-15 07:26 UTC, merged