t/22-svirt: Fix sporadic failures of `run_ssh_cmd(keep_open=>0)`
os-autoinst/os-autoinst pull request #1568
Opened 2020-11-17 15:26 UTC by cfconrad

Ticked: poo#69346
The assumption is, that the NET:SSH2 module calls DESTROY of one of the
created objects and then reuse the same memory (see _new implementation
in SSH2.xs [1]).
The "fix" is, do not use `_new` to create the class anymore. Just
blessing a HASH. And create a unique random string to identify each
instance. This identifier is used for the key in `$ssh_obj_data`.

This change is actually the minimal impact solution I found. Because we do
not use the internal `_new()` method of NET:SSH2 anymore, but getting a blessed
HASH, we could improve this code later and drop `$ssh_obj_data` completly.

[1] https://metacpan.org/source/RKITOVER/Net-SSH2-0.71/SSH2.xs#L902

2020-11-17 17:43 UTC, Martchus requested changes
Looks good besides the mentioned nitpicks.

2020-11-17 17:43 UTC, Martchus commented on t/22-svirt.t
> +            die("Identifier not uniqe") if (exists($ssh_obj_data->{$id}));
```suggestion
            die 'Identifier not unique' if exists $ssh_obj_data->{$id};
```
(style change and typo fix)

2020-11-17 17:43 UTC, Martchus commented on t/22-svirt.t
> +    $net_ssh2->mock(DESTROY => sub { });
```suggestion
    $net_ssh2->noop('DESTROY');
```

2020-11-17 23:07 UTC, cfconrad commented on t/22-svirt.t
> +    $net_ssh2->mock(DESTROY => sub { });
thx

2020-11-17 23:07 UTC, cfconrad commented on t/22-svirt.t
> +            die("Identifier not uniqe") if (exists($ssh_obj_data->{$id}));
thx

2020-11-18 11:24 UTC, Martchus approved these changes

2020-11-18 15:41 UTC, okurz approved these changes

2020-11-18 16:35 UTC, Martchus commented
I can not access OBS right now (from WiFi at SUSE office) but the failure is likely unrelated (like last time). So I suppose we can force-merge.

2020-11-20 06:15 UTC, merged