Lockapi
os-autoinst/os-autoinst pull request #1578
Opened 2020-11-30 17:19 UTC by Martchus

See https://progress.opensuse.org/issues/80264 and particular commit messages

2020-12-01 15:39 UTC, okurz requested changes
1. can you explain why you remove t/09-lockapi.t? I see it mentioned in the git commit message of https://github.com/os-autoinst/os-autoinst/pull/1578/commits/a51148739d3365b949744b646b4114f5901a8dee but it does not state a reason. I think it would be beneficial to still have a very limited unit test for lockapi only.
2. I see uncovered test output:

```
$ prove -I. -Iexternal/os-autoinst-common/lib t/30-mmapi.t 
t/30-mmapi.t .. 1/? [2020-12-01T16:37:40.923 CET] [debug] mutex create 'lucky_lock'
[2020-12-01T16:37:40.926 CET] [debug] mutex lock 'lockable'
[2020-12-01T16:37:40.929 CET] [debug] mutex try lock 'lockable'
[2020-12-01T16:37:40.932 CET] [debug] mutex unlock 'unlockable'
[2020-12-01T16:37:40.935 CET] [debug] barrier create 'lucky_barrier' for 41 tasks
[2020-12-01T16:37:40.938 CET] [debug] barrier wait 'unblocked'
[2020-12-01T16:37:40.942 CET] [debug] barrier wait 'check_dead_job_barrier'
[2020-12-01T16:37:40.945 CET] [debug] barrier try wait 'unblocked'
[2020-12-01T16:37:40.948 CET] [debug] barrier destroy 'deletable'
t/30-mmapi.t .. ok   
All tests successful.
Files=1, Tests=6,  0 wallclock secs ( 0.04 usr  0.00 sys +  0.58 cusr  0.03 csys =  0.65 CPU)
Result: PASS
```

2020-12-01 15:39 UTC, okurz commented on t/30-mmapi.t
> +    is(scalar @recorded_info,                  2, 'record info called expected number of times') or diag explain \@recorded_info;
the indentation looks a bit unusual. If you get rid of the parentheses for Test::More calls this IMHO looks better

```suggestion
    is lockapi::mutex_lock('lockable'),     1, 'mutex locked';
    is lockapi::mutex_try_lock('lockable'), 1, 'mutex locked (try)';
    is lockapi::mutex_unlock('unlockable'), 1, 'mutex unlocked';
    is lockapi::barrier_create('lucky_barrier', 41), 1, 'barrier created';
    is lockapi::barrier_wait('unblocked'), 1, 'waited for barrier';
    is $recorded_info[0]->[1], 'Wait for unblocked (on parent job)', 'info recorded by waited for barrier';
    is lockapi::barrier_wait({name => 'check_dead_job_barrier', check_dead_job => 1}), 1, 'waited for barrier with check_dead_job flag';
    is $recorded_info[1]->[1], 'Wait for check_dead_job_barrier (on parent job)', 'different info recorded with check_dead_job flag';
    is lockapi::barrier_try_wait('unblocked'), 1, 'tried waiting for barrier';
    is lockapi::barrier_destroy('deletable'),  1, 'barrier destroyed';
    is scalar @recorded_info, 2, 'record info called expected number of times' or diag explain \@recorded_info;
```

2020-12-01 15:39 UTC, okurz commented on lockapi.pm
> +use testapi;
I think an explicit `use testapi ()` can show the intention better

2020-12-01 15:39 UTC, okurz commented on t/30-mmapi.t
> +use basetest;
You don't need any of these imports if you just mock them. I tried it out, deleted all three, tests still pass :)

2020-12-01 16:04 UTC, kalikiana approved these changes
I like the clean-up, especially also the new variables that can be overridden. Might turn out handy outside of tests as well.

2020-12-01 16:04 UTC, kalikiana commented on mmapi.pm
> +Logs the errors if a log context specified.
```suggestion
Logs the errors if a log context was specified.
```

2020-12-01 16:47 UTC, Martchus commented
> can you explain why you remove t/09-lockapi.t?

This test was just bad, e.g. it pretends to check whether parameters are passes as expected but actually doesn't. It also generally doesn't check the logging. It was also written in a very verbose way. So I decided to rewrite it and include it into the mmapi test.

> I see uncovered test output

Ok, I'll try to fix that and the other things you've mentioned.

2020-12-03 11:08 UTC, okurz requested changes

2020-12-03 11:08 UTC, okurz commented on lockapi.pm
> +        sleep RETRY_INTERVAL;
codecov reports this as uncovered. Please try to cover that or mark with `# uncoverable statement`

2020-12-03 11:08 UTC, okurz commented on lockapi.pm
> +    return _api_call_with_logging_and_error_hanndling("barrier destroy '$name'",
s/hanndling/handling/

2020-12-03 12:06 UTC, okurz requested changes

2020-12-03 12:06 UTC, okurz commented on lockapi.pm
> +        sleep RETRY_INTERVAL;    # uncoverable statement
thing is: If this line is uncovered at least the one above is as well. I haven't checked the complete coverage report, just tried to explain the CI coverage analysis comment. Can you please crosscheck for complete coverage if feasible or mark uncoverable statements accordingly?

2020-12-03 13:11 UTC, Martchus commented
I've marked all lines which are hard to cover (and weren't covered by the previous test as well) as uncoverable. The only exception are the functions `wait_for_children` and `wait_for_children_to_start`. They were covered at all (also not by the previous test) so I thought it is best to actually cover them.

2020-12-03 14:18 UTC, okurz approved these changes

2020-12-03 20:44 UTC, okurz commented
Awesome work here. I have verified enough locally that the new test additions work fine so I can merge.

2020-12-03 20:44 UTC, merged