localXvnc: Output additional error context if available
os-autoinst/os-autoinst pull request #1594
Opened 2020-12-11 05:17 UTC by okurz

See https://github.com/os-autoinst/os-autoinst/pull/1411/files/94d698b595b050ece94caaf22c69de78ff242e04#diff-0d5bcd4a55204a29679ead9f0e0c43aa

2020-12-11 10:08 UTC, Martchus reviewed
Codecov says the changed line isn't tested. Maybe we should add tests at least for the error case.

2020-12-11 12:29 UTC, okurz commented
hm, isn't `$@` set by eval? But ok, we can try to come up with more tests.

2020-12-11 13:26 UTC, Martchus commented
> hm, isn't $@ set by eval?

Likely the thinking was that system doesn't throw an exception if the command just exists with a non-zero exit code and one would usually check `$?` for that. We're using autodie here so I'm not sure how it behaves in this case.

2020-12-11 13:32 UTC, okurz commented
oh, I understand now. Of course we would not except an error from system I guess. Well, ok, let's see if I can come up with a test for that and we might find out that we can just remove that :)

2021-07-28 08:26 UTC, Martchus commented on consoles/localXvnc.pm
> +    die "cant' start xterm on $display (err: $! retval: $?, $@)" if $@;
You could also fix the

2021-07-28 11:52 UTC, okurz commented
I now got rid of the die-line completely as I think we do not need it at all. Tested manually within a perl debug session. For example specifying an invalid display number like ":23523" causing xterm to throw the error "xterm: Xt error: Can't open display: :26236" which however does not trigger `system` to throw an exception so the behaviour in this regard is unchanged.

2021-07-28 12:20 UTC, Martchus requested changes
This now lacks proper error handling. As mentioned in previous comments, the check for `$@` was not that useful but `$!` should be checked.

Note that xterm's output is not sufficient, e.g. there can still be other errors:

```
  DB<7> system('xterm2 foo bar');
  DB<8> die "cant' start xterm on $display (err: $! retval: $?)" if $!;
cant' start xterm on  (err: No such file or directory retval: -1) at (eval 14)[/usr/lib/perl5/5.32.1/perl5db.pl:738] line 2.
```

(Not sure whether we should actually die here, though.)

2021-07-28 12:53 UTC, okurz commented
> This now lacks proper error handling. As mentioned in previous comments, the check for `$@` was not that useful but `$!` should be checked.
> 
> Note that xterm's output is not sufficient, e.g. there can still be other errors:
> 
> ```
>   DB<7> system('xterm2 foo bar');
>   DB<8> die "cant' start xterm on $display (err: $! retval: $?)" if $!;
> cant' start xterm on  (err: No such file or directory retval: -1) at (eval 14)[/usr/lib/perl5/5.32.1/perl5db.pl:738] line 2.
> ```
> 
> (Not sure whether we should actually die here, though.)

If you find a better error example then maybe we would still need the error handling but we already ensure that the command is callable in the lines in before with `which`. This would already die if the command either points to an invalid application or if it's not actually executable.

2021-07-28 13:18 UTC, Martchus commented
I still think the correct way is to handle the error, e.g. the file might be removed or no longer be executable after the `which` call.

I also found that catching en exception is required after all, e.g. to handle the case when the binary is corrupted:
```
  DB<12> system('xterm2 foo bar');
/usr/bin/xterm2: Zeile 1: foo: Kommando nicht gefunden.
```

or if a shared library is missing:

```
  DB<13> system('xterm2 foo bar');
xterm2: error while loading shared libraries: libc++utilities-git.so.5: cannot open shared object file: No such file or directory
```

2021-07-28 14:45 UTC, okurz commented
> I still think the correct way is to handle the error

effectively we still "handle the error", just not explicitly in this step. Right now it's broken because

```
eval { system('xterm2 foo bar') };
die "error caught" if $@;
```

likely never triggers the "die", as @perlpunk correctly noted in https://github.com/os-autoinst/os-autoinst/pull/1411/files/94d698b595b050ece94caaf22c69de78ff242e04#diff-0d5bcd4a55204a29679ead9f0e0c43aa . I am simply removing the effectively "dead code". Do we want to change the behaviour? Then I would just replace `if $@` with `if $?`, how about that?

2021-07-28 15:03 UTC, Martchus commented
> I am simply removing the effectively "dead code".

As stated in my last comment, this is not "dead code". It runs if the binary has been corrupted, a library is missing or possibly for further reasons like exceeding the max. number of processes.

The `$?` is a different case. All cases it would catch *might* be covered by the `which`-check - although it might not cover all and the file might be removed after the `which`-check. I consider the `$?` less important as the cases when it can happen despite the `which`-check are a bit contrived (but still possible).

2021-07-28 15:11 UTC, okurz commented
> > I am simply removing the effectively "dead code".
> 
> As stated in my last comment, this is not "dead code". It runs if the binary has been corrupted, a library is missing or possibly for further reasons like exceeding the max. number of processes.

I don't think we understand each other. If the binary has been corrupted then `system` would return with a non-zero, i.e. "false" result, not die so the `if $@` would not trigger, isn't it?

2021-07-28 15:12 UTC, Martchus commented
In my tests with the Perl debugger it dies if one runs `use autodie;` before.

2021-07-28 15:20 UTC, okurz commented
> In my tests with the Perl debugger it dies if one runs `use autodie;` before.

ah, right! I missed that part in my manual debugging session. Embarrasing considering I introduced "autodie" ;)

2021-07-28 16:28 UTC, Martchus requested changes
I guess ignoring the `$?` error cases is ok considering they are a bit contrived. Simply letting the exception pass through should be ok as well.

I'm only requesting changes because the test contains many out-commented lines.

2021-07-28 20:14 UTC, okurz commented on t/33-consoles-localxvnc.t
> +# TODO this fails being unable to find the error string but instead states
Someone has an idea here?

2022-01-17 16:35 UTC, okurz commented
I give up

2022-01-17 16:35 UTC, closed without merging