Make hyperv powershell commands work in non-interactive ssh session
os-autoinst/os-autoinst pull request #1631
Opened 2021-03-09 14:16 UTC by pdostal

As some Hyper-V PowerShell commands in Windows Server 2019 require
interactive SSH session we need to change this behavior using
special variables provided in each SSH call.

- os-autoinst: os-autoinst/os-autoinst-distri-opensuse#12098
- Verification run: [Win2k19](http://pdostal-server.suse.cz/tests/11198) [Win2k16](http://pdostal-server.suse.cz/tests/11204)

2021-03-09 14:54 UTC, Martchus approved these changes
Looks good. I'm only adding the "acceptance-tests-needed" tag because currently one of the verification runs is still pending.

2021-03-09 18:51 UTC, okurz requested changes
http://pdostal-server.suse.cz/tests/11204/file/autoinst-log.txt turned out to be incomplete:

```
[0m[32m[2021-03-09T15:49:12.700 CET] [debug] >>> testapi::_check_backend_response: match=text-logged-in-root,tty5-selected timed out after 180 (assert_screen)
[0m[37m[2021-03-09T15:49:12.729 CET] [debug] post_fail_hook failed: no candidate needle with tag(s) 'tty5-selected, text-logged-in-root' matched
[0m[37m[2021-03-09T15:49:12.731 CET] [debug] Loading a VM snapshot lastgood
[0m[2021-03-09T15:49:12.732 CET] [debug] <<< backend::baseclass::run_ssh_cmd(cmd="powershell -Command \"\$ProgressPreference='SilentlyContinue'; Restore-VMSnapshot -VMName openQA-SUT-8 -Name lastgood -Confirm:\$false\"", keep_open=1, wantarray=0)
[2021-03-09T15:49:12.732 CET] [debug] <<< backend::baseclass::run_ssh(cmd="powershell -Command \"\$ProgressPreference='SilentlyContinue'; Restore-VMSnapshot -VMName openQA-SUT-8 -Name lastgood -Confirm:\$false\"", keep_open=1, wantarray=0)
[2021-03-09T15:49:12.732 CET] [debug] <<< backend::baseclass::new_ssh_connection(keep_open=1, blocking=1, wantarray=0)
[33m[2021-03-09T16:05:26.490 CET] [info] ::: backend::baseclass::die_handler: Backend process died, backend errors are reported below in the following lines:
Unable to create SSH channel for executing "powershell -Command "$ProgressPreference='SilentlyContinue'; Restore-VMSnapshot -VMName openQA-SUT-8 -Name lastgood -Confirm:$false"": no libssh2 error registered at /usr/lib/os-autoinst/backend/baseclass.pm line 1416.

[0m[37m[2021-03-09T16:05:26.490 CET] [debug] Closing SSH serial connection with openqaw5-xen-1.qa.suse.de
[0m[37m[2021-03-09T16:05:26.491 CET] [debug] Destroying openQA-SUT-8 virtual machine
[0m[2021-03-09T16:05:26.491 CET] [debug] <<< backend::baseclass::run_ssh_cmd(cmd="powershell -Command Stop-VM -Force -VMName openQA-SUT-8 -TurnOff", keep_open=1, wantarray=0)
[2021-03-09T16:05:26.491 CET] [debug] <<< backend::baseclass::run_ssh(cmd="powershell -Command Stop-VM -Force -VMName openQA-SUT-8 -TurnOff", wantarray=0, keep_open=1)
[2021-03-09T16:05:26.491 CET] [debug] <<< backend::baseclass::new_ssh_connection(blocking=1, wantarray=0, keep_open=1)
[31m[2021-03-09T16:05:26.492 CET] [warn] !!! backend::baseclass::run_capture_loop: capture loop failed Unable to create SSH channel for executing "powershell -Command Stop-VM -Force -VMName openQA-SUT-8 -TurnOff": Unable to send channel-open request (-7 LIBSSH2_ERROR_SOCKET_SEND) at /usr/lib/os-autoinst/backend/baseclass.pm line 1416.

[0m[37m[2021-03-09T16:05:26.492 CET] [debug] sending magic and exit
[0m[37m[2021-03-09T16:05:26.492 CET] [debug] received magic close
```

2021-03-10 08:00 UTC, okurz commented on t/22-svirt.t
> +    is($svirt->run_ssh_cmd(qq($ps "\$ProgressPreference='SilentlyContinue'; Remove-VM -Force -VMName $vmname"), 0, 'Hyper-V command successful exit');
from test results:

```
[  136s] 3: Global symbol "$ps" requires explicit package name (did you forget to declare "my $ps"?) at ./22-svirt.t line 198.
[  136s] 3: Type of arg 1 to Test::Exception::dies_ok must be block or sub {} (not reference constructor) at ./22-svirt.t line 286, near ""die() when log file wasn't created")"
[  136s] 3: Type of arg 1 to Test::Exception::dies_ok must be block or sub {} (not reference constructor) at ./22-svirt.t line 291, near "'die() when emulate CONSOLE_EXIT token in log file')"
[  136s] 3: Execution of ./22-svirt.t aborted due to compilation errors.
[  136s] 3: [07:44:48] ./22-svirt.t ............................. 
```

2021-03-10 08:42 UTC, pdostal commented
> http://pdostal-server.suse.cz/tests/11204/file/autoinst-log.txt turned out to be incomplete:

The worker was in my opinion overtaken by another test from another instance. It succeeded after restart.

> Looks good. I'm only adding the "acceptance-tests-needed" tag because currently one of the verification runs is still pending.

I added one more test case but honestly I don't know what else to add.

I also added a VR on Win2k12r2.

2021-03-10 09:06 UTC, okurz approved these changes
Verification runs are all fine so we can regard this as acceptable. Thank you so far. We would really appreciate if you could also help increase the test coverage for the files as reported by codecov. E.g. with mocked methods have a unit test statement coverage for the files you changed. This can be done in a follow-up PR.

2021-03-10 09:35 UTC, Martchus commented
Your passed verification run has the reason:

>  Result: passed finished about 8 hours ago ( 01:26 hours )
Reason: backend done: Unable to create SSH channel for executing "powershell -Command "if ($(Get-VM -VMName openQA-SUT-8 | Where-Object {$_.state -eq 'Off'})) { exit 1 } else { exit 0 }"": no libssh2 error registered at /usr/lib/os-autoinst/backend/baseclass.pm line 1416. 

That's a little bit strange but likely the pool directory just wasn't clean when running the job.

2021-03-10 10:41 UTC, okurz requested changes
oh, good catch. I would prefer if this is being looked into first anyway. At best the case of unclean pool dir can be handled as well.

2021-03-10 13:57 UTC, mloviska commented
> Your passed verification run has the reason:
> 
> > Result: passed finished about 8 hours ago ( 01:26 hours )
> > Reason: backend done: Unable to create SSH channel for executing "powershell -Command "if ($(Get-VM -VMName openQA-SUT-8 | Where-Object {$_.state -eq 'Off'})) { exit 1 } else { exit 0 }"": no libssh2 error registered at /usr/lib/os-autoinst/backend/baseclass.pm line 1416.
> 
> That's a little bit strange but likely the pool directory just wasn't clean when running the job.

Look like the same issue as we can see in vmware tests described in https://progress.opensuse.org/issues/81878 or in https://progress.opensuse.org/issues/44771

2021-03-11 10:13 UTC, Martchus requested changes
The auto-generated Makefiles should not be checked in. Note that the project moved to CMake now so we've cleaned up `.gitignore`.

2021-03-11 10:34 UTC, pdostal commented
@okurz @Martchus this PR should now be ready. I will try to improve the test coverage in another PR.

2021-03-11 10:44 UTC, Martchus approved these changes
Ok. About extending tests: There's already `22-svirt.t` which might serve as a starting point.

2021-03-11 10:47 UTC, okurz commented
@pdostal can you comment on https://github.com/os-autoinst/os-autoinst/pull/1631#issuecomment-795153394 regardin the errors encountered in the verification runs even though they don't fail?

2021-03-11 10:51 UTC, pdostal commented
> @pdostal can you comment on [#1631 (comment)](https://github.com/os-autoinst/os-autoinst/pull/1631#issuecomment-795153394) regardin the errors encountered in the verification runs even though they don't fail?

I don't know much more than @mloviska already stated. This issue is not related to this PR, is not Hyper-V specific and is handled in [poo#81878](https://progress.opensuse.org/issues/81878) separately.

2021-03-11 11:24 UTC, Martchus commented
And the fact that the *passed* test shows that reason is likely just due to a dirty pool directory or some other unrelated setup problems.

2021-03-11 11:29 UTC, okurz approved these changes
ok then :)

2021-03-11 11:30 UTC, merged