[WIP] Make ipmi SOL console persistent
os-autoinst/os-autoinst pull request #1652
Opened 2021-04-21 06:22 UTC by czerw

Persistent console is already implemented for PowerVM and it works
without issue. Ipmo SOL console needs the same approach. Internal
openQA console for SOL should be alive all the time during the test
without stopping and strating it again.

Progress: https://progress.opensuse.org/issues/60437

Verifications:

2021-04-21 06:36 UTC, okurz requested changes
s/Ipmo/IPMI/
s/strating/starting/

2021-04-21 07:22 UTC, pdostal approved these changes

2021-04-21 07:35 UTC, czerw commented
@alice-suse @Julie-CAO Could you please recommend some bare metal job from VT testing for verification?

2021-04-21 08:10 UTC, Julie-CAO commented
> @alice-suse @Julie-CAO Could you please recommend some bare metal job from VT testing for verification?

Hi Petr,
the ipmi sol console is lost after typing 'reboot' in this test
https://openqa.nue.suse.com/tests/5840869#step/reboot_and_wait_up_normal/8

 if it is just the case the PR fixes, the test is suitable. We met this ipmi problem on the DELL AMD machine which was added to OSD one month ago, ipmi sol console always lost after the second reboot.  we have to remove the machine from our product testing pool, and create a particular test for further investigation. You can use this test to verify. One of our SUT will be saved if the ipmi is fixed. Let me know if I can help.

2021-04-21 09:44 UTC, czerw commented
> You can use this test to verify. One of our SUT will be saved if the ipmi is fixed. Let me know if I can help.
@Julie-CAO Verification passed, link is in description.

2021-04-21 09:53 UTC, czerw commented
@frankenmichl @pevik @mdoucha just fyi

2021-04-21 09:55 UTC, okurz requested changes
Please link a ticket in the git commit message as well.

Awaiting the verification of VT tests.

EDIT: ok, I see that verification jobs are ok so far

2021-04-21 10:28 UTC, czerw commented
> Please link a ticket in the git commit message as well.

Done, not sure why I didn't (cause I always do) :)

2021-04-21 10:55 UTC, Martchus reviewed
Looks generally good. Does tidy require spreading this over 3 lines?

2021-04-21 11:00 UTC, czerw commented
> Looks generally good. Does tidy require spreading this over 3 lines?

Nope, just my style, fixed.

2021-04-21 11:35 UTC, Julie-CAO commented
> > You can use this test to verify. One of our SUT will be saved if the ipmi is fixed. Let me know if I can help.
> > @Julie-CAO Verification passed, link is in description.

Amazing, two verification runs passed. Can we have more runs to confirm it is fixed?  such as 5 runs, as the test did not fail every time.

2021-04-21 11:45 UTC, okurz approved these changes

2021-04-21 11:45 UTC, merged

2021-04-21 14:29 UTC, czerw commented
> Amazing, two verification runs passed. Can we have more runs to confirm it is fixed? such as 5 runs, as the test did not fail every time.

I run your job 5 times in total and it was fine all the time, see http://black-bit.suse.cz/tests/147#next_previous. You can try to put your job into production schedule when is this change deployed on OSD.

2021-04-22 01:08 UTC, Julie-CAO commented
> > Amazing, two verification runs passed. Can we have more runs to confirm it is fixed? such as 5 runs, as the test did not fail every time.
> 
> I run your job 5 times in total and it was fine all the time, see http://black-bit.suse.cz/tests/147#next_previous. You can try to put your job into production schedule when is this change deployed on OSD.

Cool! You save one machine for us! and maybe more machines in the future :+1:

2021-04-22 03:11 UTC, alice-suse commented
@czerw Sorry for the late reply. I was on FTO yesterday. Thanks for the efforts to fix  poo#60437. However I would **suggest to make the sol console persistent option configurable via /etc/openqa/workers.ini,** which is needed for 
different ipmi vendor machines(having different born ipmi stability) and different test purpose it serves (hours long jobs or minutes short jobs -- the longer job, the less stable sol becomes, the higher chance needed for non-persistent console).

I know that you have provided VT validation tests based on the job that julie provided. Thanks for it. But the SUT that it's configured to is a new machine that we recently get, which has definitely different ipmi behavior compared to our other ipmi machines, just told from the fact that the same automation code running on it meets ipmi issues while all other machines run well. Thus vice versus, when the validations on it run well , it can not promise that this change will be safe for other machines. Likely not, but it will be seen from next build new jobs.

Let me provide more background info here for ipmi console to explain why. Virtualization team has been using SUTs configured with ipmi backend for several years and we've undergone the big changes of this ipmi console usage from the very beginning(sol console only -> root-ssh console mainly + sol as less as possible -> proactive sol console reconnection  around reboot for higher stability + necessary sol reconnection when sol is detected problematic). The main reasons for above changes are:
- ipmi console itself(underlying software provided by hardware vendors, nothing related to openqa) is unstable, especially when used for long time(hours). It is actually not designed for automated testing purpose, instead designed for administration purpose which just requires usage from time to time. So it does not perform correctly and stablely for long time automation tests, eg several hours which VT jobs are. So that's why sol console is not configured to be persistent .
- different SUT vendors ipmi technology is different and performance during long test time job is different, some better while some worse. So it is better to make persistent option configurable in worker config.
- when sol console becomes unstable, no matter due to long time usage or unluckily short time usage, try to reconnect console can survive with high chance(not always either). So this is why we even proactively reset it before using it around reboot during test.

2021-04-22 05:47 UTC, czerw commented
@alice-suse Thanks for feedback, what i see from experience, the main problem when using the SOL console are around console reset, either in internal openQA console level or ipmi level:
*  proactive sol console reconnection around reboot - this is not helping anything, only masking and delaying the issue, for example 2x `reset_consoles` is not solution https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/a1d88102f2d865153f87aaa902168ae31de066bf/tests/virt_autotest/login_console.pm#L48
*  necessary sol reconnection when sol is detected problematic - this  is not changed and it should stay as it is

2021-04-22 06:32 UTC, alice-suse commented
> @alice-suse Thanks for feedback, what i see from experience, the main problem when using the SOL console are around console reset, either in internal openQA console level or ipmi level:
> 
> * proactive sol console reconnection around reboot - this is not helping anything,

I understand how you feel it this way. With your test code, ipmi SUT setup, and the specific ipmi SUT, you've been troubled by sol console reconnection for long time. But trust me, VT jobs on all osd ipmi SUTs except the recent new purchased one have been working well on sol console reconnection.

> only masking and delaying the issue, 

Unluckily, what we need is to mask or workaround the unstable ipmi console(not related to openqa layer, but ipmi console itself provided by HW vendor), so that test can continue. Our test purpose is not to test ipmi console(HW software level), but to test suse products.
However if the issue you mentioned is openqa backend level(ipmi backend and sol console), or openqa test code level, NO, this is definitely not what we want to mask or delay by resetting console.

>for example 2x `reset_consoles` is not solution https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/a1d88102f2d865153f87aaa902168ae31de066bf/tests/virt_autotest/login_console.pm#L48

Agree. To be honest, I was not aware of two lines of reset_consoles or who did that. Definitely this is what I meant to do.

> * necessary sol reconnection when sol is detected problematic - this  is not changed and it should stay as it is

Yep.