Handle a NEEDLES_DIR than contain a trailing / correctly.
os-autoinst/os-autoinst pull request #1671
Opened 2021-05-13 22:22 UTC by radolin

Currently if the NEEDLES_DIR parameter is supplied with a trailing slash it causes the first character of the filename to be stripped and json needle file is not found.

2021-05-14 09:07 UTC, okurz commented
Hi @radolin , welcom to this project :fireworks: :partying_face: . Thanks for your contribution. Looks like a sensible approach and would make code even easier to read. I like it :) Let's see what our CI tests will tell. Please correct the git commit subject line by replacing "than" with "that" and delete the dot at the end of line

2021-05-14 10:59 UTC, Martchus requested changes
This looks wrong. The existing code makes this a relative path within the needles directory. The new code removes all directories leaving only the file name. Maybe just run `File::Spec->canonpath( $path )` on both paths (`$jsonfile` and `$needles_dir`) before the `if`.

2021-05-14 17:05 UTC, radolin commented
Thanks for the warm welcome @okurz and thanks for the review @Martchus! Please have a look at my second attempt, that should keep identical behavior like the previous version.

2021-05-14 18:04 UTC, okurz commented
I suggest you extend t/01-test_needle.t accordingly to ensure the code does what you need

2021-05-17 10:31 UTC, Martchus reviewed
This should work now for your case but as @okurz mentions it would be great to extend tests (covering a sub directory and a trailing `/`). Of course it is still broken if a path contains multiple consecutive slashes (and the other doesn't) due to the `index()`-check. Hence I've suggested to run `File::Spec->canonpath()` on both paths before.

2021-05-31 13:51 UTC, Martchus commented
@radolin If we improve this we should improve it in a way so it doesn't break on the next best case like having two consecutive slashes so it would be great to update the PR accordingly. Or does my suggestion to use `File::Spec->canonpath()` has any downsides I'm not seeing?

2021-05-31 14:51 UTC, kraih commented
Have to agree with @Martchus, `canonpath()` seems reasonable here.

2021-12-01 14:25 UTC, kalikiana commented
@radolin Are you planning to update this PR? If you need help, feel free to ask 😃

2021-12-01 15:14 UTC, radolin commented
@kalikiana I'm not familiar with the Perl testing framework and will need to catch up on that. I would update it when I have some more free time, but have other priorities now. If you want to take this please feel free.

2021-12-01 15:47 UTC, okurz commented
@kraih @Martchus some of you wanting to give it a try, add tests and use `canonpath` or maybe something from `Mojo::File`?

2022-08-12 01:01 UTC, closed without merging