Add test coverage for mouse_tclick testapi function
os-autoinst/os-autoinst pull request #1701
Opened 2021-06-24 14:23 UTC by KevinKipkorir

Add subtest for assert_and_dclick in the t/03-testapi.t file.
Add new function for assert_and_dclick in the testapi.pm file.
https://progress.opensuse.org/issues/94315?next_issue_id=94303&prev_issue_id=94336

2021-06-24 20:35 UTC, okurz requested changes
https://github.com/os-autoinst/os-autoinst/pull/1700#discussion_r655924353

2021-06-24 21:10 UTC, KevinKipkorir commented
> https://github.com/os-autoinst/os-autoinst/pull/1700#discussion_r655924353

I reduced duplication on the file you suggested.Also discovered not extending the file "testapi.pm" after adding the subtest function results to failure on unit tests.

2021-06-25 07:22 UTC, kalikiana commented on testapi.pm
> +sub assert_and_tclick {
Maybe there's some confusion here. This looks quite nice but that's not what the ticket asks for 🤓️

The AC is `mouse_tclick is covered by at least one unit test`. We don't want a new API function here, just more test coverage for `mouse_tclick`.

2021-06-25 08:46 UTC, closed without merging

2021-06-25 12:47 UTC, KevinKipkorir commented
Accidentally closed it.