Use Time::Seconds instead of magic numbers
os-autoinst/os-autoinst pull request #1726
Opened 2021-07-20 07:02 UTC by okurz

2021-07-20 09:24 UTC, Martchus requested changes

2021-07-20 09:24 UTC, Martchus commented on lockapi.pm
> +        $subject .= int($args{amend} / ONE_MINUTE) . 'm' . $args{amend} % ONE_MINUTE . 's';
This misses a space after `Paused`.

2021-07-20 12:50 UTC, okurz commented on lockapi.pm
> +        $subject .= int($args{amend} / ONE_MINUTE) . 'm' . $args{amend} % ONE_MINUTE . 's';
done

2021-07-27 06:52 UTC, okurz commented
updated, ready for review

2021-07-27 10:31 UTC, Martchus approved these changes

2021-07-27 10:31 UTC, merged