Create backing file of arbitrary size for disk image
os-autoinst/os-autoinst pull request #1736
Opened 2021-07-29 15:24 UTC by mloviska

For bootable disk image testing in SLEM,MicroOS or JeOS we need to
create a disk image of different size than the image itself is shipped.
For QEMU backend this works already perfectly as this is handled well in
`OpenQA/Qemu` code.
The previous [attempt](https://github.com/os-autoinst/os-autoinst/pull/1717) lead to
openQA test run failures in loading [pre-installed
systems](https://openqa.suse.de/tests/6408034#step/boot_to_desktop/9)

- [Original issue in slem@s390x z/KVM](https://openqa.suse.de/tests/6590998#step/image_checks/7)
- VRs:
    * [sle-15-SP4-Online-s390x-Build18.1-create_hdd_textmode@s390x-kvm-sle12](http://kepler.suse.cz/tests/6274)
    * [sle-15-SP4-Online-s390x-Build18.1-qemu@s390x-kvm-sle12](http://kepler.suse.cz/tests/6276)
    * [slem image-checks](http://kepler.suse.cz/tests/6268#step/image_checks/4)
    * [JeOS with HDDSIZEGB_1=100](http://kepler.suse.cz/tests/6259)
    * [JeOS with HDDSIZEGB_1=undef](http://kepler.suse.cz/tests/6258)

2021-07-29 15:25 UTC, mloviska commented
Hello @Soulofdestiny @jlausuch @Vogtinator, you have a look, pls?

2021-07-29 15:26 UTC, okurz requested changes
Please add tests.

Also I consider the function add_disk very complicated already. I suggest to extract some parts before adding more.

2021-07-29 16:30 UTC, jlausuch commented on consoles/sshVirtsh.pm
> +                if (($size * 1024 * 1024 * 1024) <= $image_vsize) {
```suggestion
                $size = (($size * 1024 * 1024 * 1024) <= $image_vsize) ? $image_vsize : $size . 'G'
```

if you prefer 1 liner, but ok with current implementation :)

2021-07-29 16:31 UTC, jlausuch commented
LGTM, but I guess you need to add the unit tests.

2021-07-30 07:18 UTC, jlausuch commented on consoles/sshVirtsh.pm
> +                    $size = $image_vsize;
I guess you don´t need these lines any more.

2021-07-30 07:18 UTC, jlausuch commented on consoles/sshVirtsh.pm
> +                $size = (($size * 1024 * 1024 * 1024) <= $image_vsize) ? $image_vsize : $size . 'G'
```suggestion
                $size = (($size * 1024 * 1024 * 1024) <= $image_vsize) ? $image_vsize : $size . 'G';
```

2021-07-30 07:28 UTC, mloviska commented on consoles/sshVirtsh.pm
> +                $size = (($size * 1024 * 1024 * 1024) <= $image_vsize) ? $image_vsize : $size . 'G'
I have rebased it, thanks!

2021-07-30 07:38 UTC, jlausuch reviewed
LGTM but would like os-autoinst experts to review.

2021-07-30 08:41 UTC, okurz commented
As you can see in the failed coverage check the patch coverage is too low. Meaning that there is no or too little test coverage of the changed lines of code. So https://github.com/os-autoinst/os-autoinst/pull/1736#pullrequestreview-718236676 still applies. If you state explicitly that you don't want to or can't do that then we can try to help or accept the change without as exception but for long-term sustainability I suggest to look into proper tests

2021-07-30 14:29 UTC, jlausuch commented
> As you can see in the failed coverage check the patch coverage is too low. Meaning that there is no or too little test coverage of the changed lines of code. So [#1736 (review)](https://github.com/os-autoinst/os-autoinst/pull/1736#pullrequestreview-718236676) still applies. If you state explicitly that you don't want to or can't do that then we can try to help or accept the change without as exception but for long-term sustainability I suggest to look into proper tests

Since this is a minor change on something that was not even covered before (tests are not covering function `add_disk`), would it be ok to postpone the UT for later (a poo could be created for it) and merge this as it is? Anyway, with this PR, the coverage is just reduced 0.04% which is not very significant...

2021-07-30 14:34 UTC, merged

2021-08-01 07:47 UTC, jlausuch commented
Thanks!