consoles::sshVirtsh: Make second argument to define_and_start optional
os-autoinst/os-autoinst pull request #1762
Opened 2021-09-03 09:59 UTC by okurz

The problem was introduced in
https://github.com/os-autoinst/os-autoinst/pull/1753. This should fix
some failed openQA tests that fail on this method.

Related progress issue: https://progress.opensuse.org/issues/98087

2021-09-03 10:02 UTC, perlpunk requested changes
From my findings, `$args` can be removed completely, it's not used, and code calling this method never pass a second argument.

2021-09-03 10:13 UTC, okurz commented
Right, changed. Thank you

2021-09-03 10:24 UTC, perlpunk approved these changes

2021-09-03 10:24 UTC, merged

2021-09-06 08:42 UTC, mloviska commented
After some changes done to svirt related files ( I guess the signatures update has revealed it ) we can see [Too few arguments for subroutine 'consoles::sshVirtsh::stop_serial_grab' at /usr/lib/os-autoinst/backend/baseclass.pm line 838.
 at /usr/lib/os-autoinst/backend/console_proxy.pm line 65](https://openqa.suse.de/tests/7029546#step/patch_and_reboot/128) failures.

If I haven't overlooked something `stop_serial_grab` does not make use of `$args` either.
https://github.com/os-autoinst/os-autoinst/blob/master/backend/svirt.pm#L340 
https://github.com/os-autoinst/os-autoinst/blob/master/consoles/sshVirtsh.pm#L567

2021-09-06 08:46 UTC, perlpunk commented
@mloviska handled in #1763

2021-09-06 08:57 UTC, mloviska commented
> @mloviska handled in #1763

Thanks!