Install fonts-config needed by x3270 and require everything
os-autoinst/os-autoinst pull request #1770
Opened 2021-09-14 12:48 UTC by asdil12

Recommends don't work in containers

Only leave `dumponlyconsole` as a recommend as nothing
seems to provide it.

Ticket: https://progress.opensuse.org/issues/97751

2021-09-14 13:00 UTC, Martchus reviewed
I would rather provide a split package `os-autoinst-full` similar to `qemu-kvm` which we already provide that has all the dependencies as `Requires`. You just needed to add another `%package` block below. (To avoid redundancy, use a macro instead of listing dependencies twice.)

2021-09-14 13:05 UTC, Martchus commented
Just for the record: We've just been debugging x3270 startup problems in a minimal containerized environment and the missing font-config prevented it to start. Not sure why it was never a problem before (even when we used containers previously on another host).

2021-09-15 09:38 UTC, okurz requested changes
As stated elsewhere I am against requiring all these s390x specific components into generic os-autoinst.
For the ticket at hand please prioritize coming up with a quick-and-dirty solution, e.g. `podman run … bash` to have an interactive prompt in the container, do all what is necessary in the interactive bash session to have at least one s390x job completing and store that in a dirty shell script.

2021-09-16 13:44 UTC, asdil12 commented
> As stated elsewhere I am against requiring all these s390x specific components into generic os-autoinst.
> For the ticket at hand please prioritize coming up with a quick-and-dirty solution, e.g. `podman run … bash` to have an interactive prompt in the container, do all what is necessary in the interactive bash session to have at least one s390x job completing and store that in a dirty shell script.

This would lead to broken jobs (the worker is already running when running `podman exec`) or raise conditions (if the worker is in that moment installing `os-autoinst-distri-opensuse-deps`).

If I create such a dirty bash script, that should be https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/install_deps.sh. Or https://github.com/os-autoinst/openQA/blob/master/container/worker/Dockerfile.

And with the new subpkg we should have a single additional package to put in there.

2021-09-16 14:38 UTC, Martchus approved these changes

2021-09-17 08:26 UTC, merged