baseclass: Increase default value of _CHKSEL_RATE_HITS
os-autoinst/os-autoinst pull request #1857
Opened 2021-11-19 11:56 UTC by cfconrad

Ticket: https://progress.opensuse.org/issues/60161

This just double the allowed read attempts in 30s. For tests, which do a
lot on the console, 15k isn't enough.
Actually we can easily trigger up to 55k by a simple
```perl
while(1) { script_output('true', quiet => 1) };
```
loop, but I thought double it, will fix most of the seen problems as an
interim solution.

http://openqa-3.wicked.suse.de/tests/31388 with _CHKSEL_RATE_HITS=15000 => FAILED
http://openqa-3.wicked.suse.de/tests/31387 with _CHKSEL_RATE_HITS=100000 => SUCCESSFUL

2021-11-19 13:09 UTC, Martchus approved these changes
I suppose this is ok. I've been adding the "not-ready" label to give more people the chance to review (before mergify would merge it automatically).

2021-11-19 13:11 UTC, Martchus commented
By the way, since this is read from a test variable you could also just increase the value on tests which need it.

2021-11-19 20:09 UTC, cfconrad commented
Yeah sure, this is what I do so far. In my environment I set this value to 60k in the workers config.

2021-11-21 14:21 UTC, okurz requested changes
Can you please rephrase the git commit message subject line (and maybe also the details) to describe the *Why* more than the *What*, also see https://chris.beams.io/posts/git-commit/ about this. So far I don't understand why you do this, what you want to achieve, what problem to fix, what's the effect and potential side-effects. Think how a reader of openqa.opensuse.org/changelog would see your subject (only the subject is shown for each commit) "baseclass: Increase default value of _CHKSEL_RATE_HITS" and it will likely read like "Change foo … 'cause we can" :)

2021-11-22 08:43 UTC, cfconrad commented
@okurz done, plz check

2021-11-22 09:12 UTC, okurz commented
I am sorry, it's still not clear. Why as a user should I care that you increase the default value of FOO? Try to write it in a more awesome way :) Maybe something like "Fix sporadic job failures on …" or something

2021-11-22 11:02 UTC, Martchus commented
The commit message also contains typos.

2021-11-22 14:44 UTC, cfconrad commented
@okurz There is no sporadic error or something. It is just bad code. And a good fix would be to remove it and find the cause of the actual problems that where tried to catch with it. But there is this wired parameter and it just doesn't apply to our workers power anymore. So with increasing it, we at least do not run in that **false positive** so quick anymore.

I actually think that the commit message (not looking at the typos) is ok and if later someone try to understand what was the reason for that change, he/she will get an answer from it (if not, there is the ticked and this PR). Also if someone find this variable and do a `git log --grep` he will find it.

Plz give me a complete proposal, or feel free to change it by your self.

2021-11-22 15:09 UTC, okurz commented
> Plz give me a complete proposal, or feel free to change it by your self.

If I would know something better I would tell you. The thing is I don't know why you change it at all

2021-11-22 21:10 UTC, cfconrad commented
> > Plz give me a complete proposal, or feel free to change it by your self.
> 
> If I would know something better I would tell you. The thing is I don't know why you change it at all

Because the current default value of 15k cause errors in some tests and I think the default is just not a good choice.

2021-11-22 21:31 UTC, okurz commented
> > > Plz give me a complete proposal, or feel free to change it by your self.
> > 
> > 
> > If I would know something better I would tell you. The thing is I don't know why you change it at all
> 
> Because the current default value of 15k cause errors in some tests and I think the default is just not a good choice.
> 
> Look at this comment https://progress.opensuse.org/issues/60161#note-20 it's one of the workarounds you can do to avoid it. > But I think, such a variable doesn't fit into a testsuite... so adopting the default is a better solution.

I agree. That's better. But can you please phrase the git commit message accordingly? How about "Fix errors in some tests by increasing _CHKSE_RATE_HITS" for the subject line?

2021-11-23 10:08 UTC, merged