Disable checking for VNC stalls in localXvnc
os-autoinst/os-autoinst pull request #1949
Opened 2022-02-07 15:12 UTC by Martchus

It would not work anyways because `Xvnc` stops when closing the socket
(which is done when a VNC stall is detected before establishing a new
VNC connection).

This should make it possible to revert https://github.com/os-autoinst/os-autoinst/commit/bf8e7f7ae71673046ad18a948cc2e9f7a7be9ced, see https://github.com/os-autoinst/os-autoinst/pull/1948#issuecomment-1031564322.

I needed to test it on some worker first, of course.

2022-02-11 14:39 UTC, Martchus commented
I've just tested our Xvnc setup via vncviewer (using https://github.com/os-autoinst/os-autoinst/commit/8f4205a4087bd888ff18db2b29137fa087206779) and it is indeed impossible to re-connect (when closing the connection Xvnc terminates). So I suppose this change makes generally sense. Alternatively we could change the setup to avoid Xvnc being terminated automatically (by avoiding `-inetd`). However, that would likely complicate the setup.

2022-02-11 17:05 UTC, kalikiana commented
> I've just tested our Xvnc setup via vncviewer (using [8f4205a](https://github.com/os-autoinst/os-autoinst/commit/8f4205a4087bd888ff18db2b29137fa087206779)) and it is indeed impossible to re-connect (when closing the connection Xvnc terminates). So I suppose this change makes generally sense. Alternatively we could change the setup to avoid Xvnc being terminated automatically (by avoiding `-inetd`). However, that would likely complicate the setup.

How about going with this since and a time-boxed ticket to change the setup? It could be useful, but maybe it has new side-effects

2022-02-14 10:42 UTC, Martchus commented
It took quite a while until my test job was scheduled so I've created another one (to be sure it really ran with my changes): https://openqa.suse.de/tests/8163465

> How about going with this since and a time-boxed ticket to change the setup? It could be useful, but maybe it has new side-effects

Likely we have more important things in the backlog. So I'd refrain from it unless we see a necessity for the VNC stale detection when using Xvnc. (I suppose we only saw problems with QEMU so far, right?)

2022-02-14 13:01 UTC, Martchus commented
It works, the test job already passed the critical point (where it otherwise always reliably failed without the change being reverted here).

2022-02-14 13:05 UTC, okurz requested changes
CI tests fail both in GHA and OBS

2022-02-14 13:05 UTC, okurz commented on consoles/localXvnc.pm
> +    # disable checking VNC stalls as this setup would not survive possible re-connects anyways
As you put in a good explanation in the method "request_screen_update" that you remove with this change I suggest you move at least part of that explanation here to explain why.

2022-02-14 13:20 UTC, Martchus commented
Updated the comment and adapted tests (as the mocking was no longer sufficient).

2022-02-14 13:42 UTC, okurz approved these changes

2022-02-15 13:04 UTC, kalikiana approved these changes

2022-02-15 13:05 UTC, merged