Fix a bug where the collected event was registered too late
os-autoinst/os-autoinst pull request #2001
Opened 2022-03-24 17:03 UTC by kraih

Not actually a fix for the issue i'm working on, but a small race condition i found along the way.

Progress: https://progress.opensuse.org/issues/107998

2022-03-24 17:10 UTC, Martchus reviewed
Looks good, except for the one remark mentioned in the inline comment.

2022-03-24 17:10 UTC, Martchus commented on backend/driver.pm
> +        code => sub ($process) {
Judging by RWP code additional arguments might be passed to the callback:
```suggestion
        code => sub ($process, @args) {
```

2022-03-24 17:15 UTC, Martchus approved these changes

2022-03-25 09:12 UTC, okurz requested changes
https://github.com/os-autoinst/os-autoinst/runs/5681532735?check_suite_focus=true#step:3:594 fails in 18-qemu-options.t with an error message I don't really understand.

2022-03-25 12:26 UTC, kraih commented
I've restarted the tests a few times, but `18-qemu-options.t` fails consistently in CI. Locally i'm not seeing the problem. Probably a race condition that becomes more common with the patch. I'll investigate and look for a fix.

2022-03-25 17:17 UTC, Martchus commented
Strange. Maybe the number of arguments is diverting in certain cases?

2022-03-25 17:47 UTC, kraih commented
Maybe i'll try to ssh into the GitHub Actions VM on Monday to track it down further.

2022-03-25 18:10 UTC, okurz approved these changes

2022-03-25 18:11 UTC, merged