Cleanup function and variable definition order in isotovideo
os-autoinst/os-autoinst pull request #2032
Opened 2022-04-20 08:41 UTC by okurz

2022-04-21 08:30 UTC, kalikiana requested changes

2022-04-21 10:40 UTC, okurz commented on isotovideo
> +my $backend_process;
I am "just" moving the variable declarations to top.

2022-04-21 11:27 UTC, kalikiana commented on isotovideo
> +my $backend_process;
I saw that,and I think we need to move them elsewhere without intermediate steps.

2022-04-21 12:00 UTC, Martchus commented on isotovideo
> +my $backend_process;
I also don't consider moving them to the top as intermediate improvement. When they're not at the top it is at least clear that those variables are only used by the code below. Now the variable's scope is even bigger. Note that these are not *just* variable declarations but also definitions (although they're initialized with `undef`).

2022-04-21 12:03 UTC, okurz commented on isotovideo
> +my $backend_process;
Well, it's my plan to further segment but before moving to other files I first need to understand the code and go step by step.

2022-04-21 15:04 UTC, perlpunk approved these changes

2022-04-21 15:05 UTC, perlpunk commented on isotovideo
> +my $backend_process;
As the goal is to move the subs into a module, I am ok with this intermediate step.

2022-04-22 11:42 UTC, kalikiana commented on isotovideo
> +my $backend_process;
Perhaps speaking in code will help more here: #2037

2022-04-22 13:10 UTC, Martchus commented on isotovideo
> +my $backend_process;
I don't see how this PR helps with those variables.

2022-04-22 14:46 UTC, okurz commented on isotovideo
> +my $backend_process;
I extracted functions as far as I could. I hope you agree with me that it does not make sense to define variables mixed in with subroutine definitions. So maybe the complete picture makes more sense now. But if you prefer I can move variables further down mixed in with subroutines.

2022-04-25 06:36 UTC, okurz commented on isotovideo
> +my $backend_process;
My goal is to have unit-testable code which likely means we need to move stuff to a separate, proper module file, which I would do in the next step.

2022-04-25 07:08 UTC, okurz commented
I extracted some parts of the commits here into https://github.com/os-autoinst/os-autoinst/pull/2040 which might be easier to accept as a first step.

2022-04-29 07:11 UTC, okurz commented
rebased after #2040 was merged

2022-05-03 07:49 UTC, kalikiana commented on isotovideo
> +my $backend_process;
I'll re-phrase once more. Currently the code is not well-tested. You're not adding any new tests here. It's not clear to me how you would unit test this code.

2022-05-03 11:17 UTC, kraih commented on isotovideo
> +my $backend_process;
I would make the removal of global variables a priority, that will lead to easier to maintain code.

2022-05-03 11:38 UTC, okurz commented on isotovideo
> +my $backend_process;
ok, so should I move the variables into subroutines and pass them around where necessary?

2022-05-03 12:43 UTC, kraih commented on isotovideo
> +my $backend_process;
Yea, some can probably become object properties later on. Passing them around now will make turning functions into methods quite a bit easier.

2022-06-09 10:29 UTC, Martchus commented on isotovideo
> +my $backend_process;
> I hope you agree with me that it does not make sense to define variables mixed in with subroutine definitions.

Somehow I would actually prefer to have those variables mixed in with subroutine definitions. It still limits the scope of those global variables.

> I would make the removal of global variables a priority, that will lead to easier to maintain code.

I would second that.

2022-11-04 16:32 UTC, closed without merging