Extend svirt documentation
os-autoinst/os-autoinst pull request #2043
Opened 2022-04-29 14:08 UTC by Martchus

* I've tested locally whether it works and updated and extended the
  documentation according to what works for me.
* See https://progress.opensuse.org/issues/106867

2022-04-29 15:35 UTC, perlpunk commented on doc/backends.md
> +If you add multiple instance, be sure to assign a different `VIRSH_INSTANCE` and
multiple instances

2022-04-30 12:46 UTC, okurz requested changes

2022-04-30 12:46 UTC, okurz commented on doc/backends.md
> +`systemctl start  sshd.service` under openSUSE).
Remove the double space after "start" please. Also I recommend to leave out the `.service`

2022-04-30 12:46 UTC, okurz commented on doc/backends.md
> +using `virt-manager` for viewing the created VM.
Better write "One can also use `virt-manager` ..."

2022-05-02 10:19 UTC, okurz approved these changes

2022-05-03 11:09 UTC, kraih approved these changes

2022-05-03 11:09 UTC, merged