Use htons/htonl instead of custom endian conversion code
os-autoinst/os-autoinst pull request #2096
Opened 2022-06-20 11:45 UTC by Martchus

* These functions have the same behavior of our custom
  code (they preserve the byte order on big-endian systems
  and change the byte order onn little-endian systems) so
  they should be a drop-in replacement.
* Tested the behavior also on a Tumbleweed ppc64 VM.
* See https://progress.opensuse.org/issues/111608
    * Does *not* fix the test, though.
    * Our code is also still broken when trying to
      connect to a little-endian server from a big-endian
      system (as the byte order conversion does never
      happen on big-endian systems).

2022-06-20 11:48 UTC, mimi1vx approved these changes

2022-06-20 11:52 UTC, okurz commented
>     * Tested the behavior also on a Tumbleweed ppc64 VM.

Would be nice to see an actual openQA test using that :)

2022-06-20 12:30 UTC, coolo requested changes

2022-06-20 12:34 UTC, okurz commented on ppmclibs/tinycv_impl.cc
> +        pixel = htons(pixel);
Correct. if we actually need to convert explicitly then we should use [bswap_32](https://www.gnu.org/software/gnulib/manual/html_node/bswap_005f32.html) and alike

2022-06-20 12:52 UTC, coolo commented on ppmclibs/tinycv_impl.cc
> +        pixel = htons(pixel);
(ok, the latter part is at the end of your PR description)

2022-06-20 13:14 UTC, mimi1vx approved these changes
It needs fix title

2022-06-20 13:18 UTC, Martchus commented
By the way, I've also tested that the test is actually failing if I do anything stupid in the `if (do_endian_conversion) {`-case (at least for 32-bit). Note that we also have this code which already does a byte-swap on any platform:

```
        if (do_endian_conversion) {
            red = data[offset++];
            green = data[offset++];
            blue = data[offset++];
        } else {
            blue = data[offset++];
            green = data[offset++];
            red = data[offset++];
        }
```

So this change is merely bringing the other `if (do_endian_conversion) {`-cases in line with that.

---

@AdamWill Pinging you just in case you want to test it once more.

2022-06-20 20:11 UTC, AdamWill commented
Good news - with current git master plus this PR, tests pass on s390x. thanks!

2022-06-20 20:25 UTC, okurz approved these changes

2022-06-21 05:04 UTC, coolo approved these changes

2022-06-21 05:43 UTC, merged