t: Increase timeout for sripts
os-autoinst/os-autoinst pull request #2113
Opened 2022-07-08 16:43 UTC by perlpunk

Issue: https://progress.opensuse.org/issues/113141

Especially on aarch64 builds it can happen that a command like
`isotovideo --help` exceeds the 3 seconds timeout.

Since we have the overall OpenQA::Test::TimeLimit I think it's ok to
increase the timeout.

2022-07-08 17:33 UTC, Martchus requested changes
I'm fine with that. Unfortunately 3 seconds can beat bit less for a full blown Perl Script. The only problem is a missing c in the commit message.

2022-07-08 17:35 UTC, perlpunk commented
oops. `c` added :)

2022-07-08 21:54 UTC, Martchus approved these changes

2022-07-09 21:43 UTC, okurz approved these changes

2022-07-09 21:44 UTC, merged