Add files that are now fully covered to the list in codecov config
os-autoinst/os-autoinst pull request #2187
Opened 2022-09-28 15:29 UTC by Martchus

See https://progress.opensuse.org/issues/111254#note-17

2022-09-29 11:43 UTC, okurz approved these changes

2022-09-29 13:55 UTC, okurz requested changes

2022-09-29 13:55 UTC, okurz commented on codecov.yml
>            - backend/virt.pm
How about using https://docs.codecov.com/docs/codecovyml-reference#ignore to only ignore pvm and ikvm and add `backend/` here?

2022-09-29 19:42 UTC, okurz approved these changes

2022-09-30 07:14 UTC, kalikiana approved these changes

2022-09-30 07:14 UTC, merged