Move loop into CommandHandler
os-autoinst/os-autoinst pull request #2200
Opened 2022-11-07 19:31 UTC by kalikiana

See: https://progress.opensuse.org/issues/81899

Note: Requires #2196

2022-11-09 15:41 UTC, Martchus reviewed
The use of the events looks generally good (especially considering events are already used here anyways).

2022-11-09 15:41 UTC, Martchus commented on isotovideo
> +$command_handler->on(signal => sub ($event, $sig) {
The event you're emitting is just called `sig` so this handler won't be executed.

2022-11-10 16:14 UTC, Martchus requested changes

2022-11-10 16:14 UTC, Martchus commented on isotovideo
> +$command_handler->on(signal => sub ($event, $sig) {
It looks still inconsistent. The signal is now called `signalhandler`.

2022-11-10 16:14 UTC, Martchus commented on OpenQA/Isotovideo/CommandHandler.pm
> +    $self->last_check_microseconds($last_check_microseconds);
An explicit return would be nice.

2022-11-10 16:14 UTC, Martchus commented on OpenQA/Isotovideo/CommandHandler.pm
> +    $SIG{HUP} = $signalhandler;
I'd extract that into a function, e.g. called `setup_signal_handler` and have the user calling it after constructing the object. (Assigning global variables unconditionally is not what I'd generally expect when invoking a constructor.)

2022-11-10 17:15 UTC, kalikiana commented on OpenQA/Isotovideo/CommandHandler.pm
> +    $self->last_check_microseconds($last_check_microseconds);
That's code from #2196 :-)

2022-11-11 16:01 UTC, Martchus approved these changes

2022-11-12 09:52 UTC, okurz requested changes
codecov/project/fully_covered failed

2022-11-15 05:49 UTC, okurz commented
Now patch coverage :)

2022-11-15 10:53 UTC, kalikiana commented
> Now patch coverage :)

Well, if you consider it useful I'll mark it as uncoverable. I don't fully understand why it shows up even though we isotovideo is already exempt...

2022-11-15 13:04 UTC, okurz approved these changes

2022-11-15 13:04 UTC, merged