94952 extend t/17-basetest.t
os-autoinst/os-autoinst pull request #2207
Opened 2022-11-15 13:55 UTC by r-richardson

draft for checking codecov reports

see: https://progress.opensuse.org/issues/94952

2022-11-17 22:16 UTC, Martchus approved these changes

2022-11-17 22:18 UTC, Martchus requested changes
Add the ticket reference to [Add subtest for verify_sound_image (17-basetest.t)](https://github.com/os-autoinst/os-autoinst/pull/2207/commits/8701cf6816850bfe14e382b0a68c71f95595086c) as well.

2022-11-17 22:18 UTC, Martchus commented on t/17-basetest.t
> +
```suggestion
```

2022-11-21 10:30 UTC, Martchus approved these changes

2022-11-21 10:35 UTC, okurz commented
please squash the "fix typo" commit at least with another commit.

2022-11-21 16:06 UTC, Martchus approved these changes

2022-11-21 17:15 UTC, kalikiana approved these changes

2022-11-21 17:16 UTC, merged