Resolve ip for iscsi hostname
os-autoinst/os-autoinst pull request #2219
Opened 2022-11-24 12:09 UTC by jknphy

2022-11-24 13:43 UTC, okurz requested changes
The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

2022-11-24 13:58 UTC, Martchus approved these changes

2022-11-24 13:58 UTC, Martchus commented on backend/qemu.pm
> +            sp('append', "dhcp && sanhook iscsi:" . "$worker_ip" . "::3260:1:$vars->{NBF}", no_quotes => 1);
```suggestion
            die "Unable to determine worker IP from WORKER_HOSTNAME\n" unless $worker_ip;
            sp('append', "dhcp && sanhook iscsi:${worker_ip}::3260:1:$vars->{NBF}", no_quotes => 1);
```

2022-11-24 13:59 UTC, Martchus requested changes
Clicked the wrong button on my previous review.

2022-11-28 05:54 UTC, jknphy commented
Thanks for the feedback. Changes addressed, it would be great to deploy this change before next SLE-15-SP5 build to see if it helps with those multiple iscsi issues seen.

2022-11-28 10:34 UTC, Martchus approved these changes

2022-11-28 12:45 UTC, okurz approved these changes

2022-11-28 12:46 UTC, merged