Show escped version of keyboard emulator server return
os-autoinst/os-autoinst pull request #2224
Opened 2022-11-29 13:47 UTC by asdil12

Log lines will look like this:
```
[2022-11-29T14:44:04.481416+01:00] [debug] Keyboard emulator says: "type: root\n"
```

2022-11-29 13:52 UTC, perlpunk approved these changes

2022-11-29 14:23 UTC, Martchus approved these changes
I'll approve but next time move this duplicated code into a separate function.

2022-11-29 14:54 UTC, perlpunk requested changes
Oops, there is a typo in the title and commit message

2022-11-29 15:55 UTC, asdil12 commented
> Oops, there is a typo in the title and commit message

Fixed

2022-11-29 15:59 UTC, okurz requested changes
I suggest to un-duplicate the code. Three lines of identical code is enough to warrant a small refactoring

2022-11-29 16:24 UTC, asdil12 commented
> I suggest to un-duplicate the code. Three lines of identical code is enough to warrant a small refactoring

you asked for it ;)

2022-11-29 17:05 UTC, Martchus commented on consoles/video_stream.pm
>      }
The new function could also return `{}`, then this code and the other occurrence boil down to:
```suggestion
    return $self->keyboard_emulator_cmd(type => $args->{text}) if $bmwqemu::vars{GENERAL_HW_KEYBOARD_URL};
```

2022-11-30 11:37 UTC, perlpunk approved these changes

2022-11-30 12:00 UTC, Martchus approved these changes

2022-11-30 12:44 UTC, merged