Mark uncoverable statements in tests
os-autoinst/os-autoinst pull request #2239
Opened 2023-01-05 10:06 UTC by mimi1vx

2023-01-05 10:11 UTC, baierjan requested changes

2023-01-05 10:15 UTC, baierjan approved these changes

2023-01-05 11:34 UTC, perlpunk commented on t/14-isotovideo.t
> +    package FakeBackendDriver;    #uncoverable statement
```suggestion
    package FakeBackendDriver;    # uncoverable statement
```

2023-01-06 09:22 UTC, perlpunk approved these changes

2023-01-06 09:23 UTC, merged