Update backend_vars.asciidoc
os-autoinst/os-autoinst pull request #2242
Opened 2023-01-11 17:48 UTC by srbala

Simple typo fix.

```log
[2023-01-11T15:59:33.346235Z] [info] cmdsrv: daemon reachable under http://*:20013/_kAZUTRYVbxZFm3E/
[2023-01-11T15:59:33.347694Z] [info] Listening at "http://0.0.0.0:20013"
Web application available at http://0.0.0.0:20013
```

2023-01-11 18:54 UTC, Martchus requested changes

2023-01-11 18:54 UTC, Martchus commented on doc/backend_vars.asciidoc
> +QEMUPORT;integer;20003 + worker instance * 10;Port on which QEMU monitor should listen
I think 20002 is actually correct, e.g. check the assignment in https://github.com/os-autoinst/openQA/blob/master/lib/OpenQA/Worker/Settings.pm. Note that the command server port is "+ 1" (see https://github.com/os-autoinst/os-autoinst/blob/master/OpenQA/Isotovideo/Runner.pm) but this is about `QEMUPORT` itself.

2023-01-12 06:39 UTC, mimi1vx commented
please squash commits,

2023-01-12 11:20 UTC, Martchus commented
We can also squash via GitHub's merge button. So it LGTM now. However, I won't approve "officially" so mergify won't merge it automatically.

2023-01-12 11:23 UTC, merged