Drop setting of TESSDATA_PREFIX in invoke-tests
os-autoinst/os-autoinst pull request #2303
Opened 2023-04-19 23:13 UTC by AdamWill

It's not appropriate to do this here. This is not the right path on all distros. Forcing this path here makes it impossible to run the tests successfully on e.g. Fedora, where the tesseract data is in /usr/share/tesseract/tessdata (and there is no need to explicitly specify this, as tesseract is built to find it there without any such specification).

2023-04-19 23:14 UTC, AdamWill commented
My first idea here was:

    if [[ -z "$TESSDATA_PREFIX" ]]; then
        # set TESSDATA_PREFIX for 02-test_ocr.t
        export TESSDATA_PREFIX='/usr/share/tessdata/'
    fi

but on second thoughts that still doesn't seem right. tesseract finds its data files just fine on Fedora with no explicit setting of `TESSDATA_PREFIX`, so we shouldn't have to explicitly set it just to make this script not override it.

If this needs to be set to make things work in CI for some reason, it needs to be done somewhere else that is specific to the CI process, not somewhere that gets used whenever the tests are run anywhere.

2023-04-20 04:49 UTC, okurz requested changes
I agree. Also we should try to rely less on the invoke tool. I would like to eventually not need it again anymore. But we should only merge this PR if the setting is provided where it's actually still needed

2023-04-20 06:02 UTC, AdamWill commented
well, the CI checks passed (except fullstack, where the failure doesn't seem to be anything to do with this), so I don't know where else it would be needed. The RPM spec sets it the same as this file previously did. I did look around but couldn't see anywhere else it would be needed.

2023-04-20 06:03 UTC, AdamWill commented
We can tag @mimi1vx , who added this - do you remember why? The commit message just says "Export TESSDATA_PREFIX in check phase of os-autoinst.spec", it does not say why it also adds it to `invoke-tests`.

2023-04-20 08:43 UTC, okurz approved these changes
yeah, it looks fine so maybe we don't actually need it in invoke-tests

2023-04-20 08:52 UTC, Martchus commented
I've re-triggered the fullstack test as it just failed during the package installation. Let's see whether it passes with this change.

2023-04-21 10:00 UTC, mimi1vx commented
@AdamWill because opensuse tumbleweed package uses nonstandard data dir :D and I added TESSDATA_PREFIX to all possible places to be safe

2023-04-21 10:00 UTC, mimi1vx approved these changes

2023-04-21 10:01 UTC, merged