Add s390x support to QEMU backend
os-autoinst/os-autoinst pull request #2309
Opened 2023-04-28 20:36 UTC by LKHN

These virtual devices added for s390x virtualization:

- `virtio-scsi` as alias of `virtio-scsi-ccw` for SCSI controller
- `virtio-gpu` as alias of `virtio-gpu-ccw` for VirtIO GPU Device
- `virtio-rng` as alias of `virtio-rng-ccw` for VirtIO RNG
- `virtio-tablet` as alias of `virtio-tablet-ccw` for input mouse interaction
- `virtio-keyboard` as alias of `virtio-keyboard-ccw` for keyboard interaction

Disabled audio support since there is no audio virtual device available on this architecture (see `qemu-kvm -device help`)

2023-05-02 10:43 UTC, Martchus requested changes
I suppose all of this is generally not very problematic because we don't use the QEMU backend for s390x test at SUSE (so it won't break existing use cases). However, tests need to be adapted (to pass again) and supposedly also extended (to cover all newly introduced code paths).

2023-05-02 10:43 UTC, Martchus commented on backend/qemu.pm
> +            unless ($is_s390x) { sp('device', 'usb-tablet'); }
This looks rather odd; I would prefer our normal coding style:
```suggestion
            sp('device', 'usb-tablet') unless $is_s390x;
```

2023-05-02 10:43 UTC, Martchus commented on backend/qemu.pm
> +    unless ($is_s390x) {
```suggestion
    if (!$is_s390x) {
```

2023-05-03 17:42 UTC, LKHN commented
@Martchus Thanks for the review.

I fixed the not passing tests and applied your suggestion. Thanks a lot!

Another issue that I tried to extend the tests with asserting QEMU parameters for s390x. However it fails due the mixed QEMU parameters from the previous tests. How can I generate the QEMU parameters which are use only variables I set for s390x?


Test - https://github.com/LKHN/os-autoinst/commit/8680ff66c6af1cf59499b01cb622c2800d29e766#diff-2c6d71750f92f3631c01e08b2695ed0a936acb082240f62d5c6162ddb5c04ce7
Error - https://github.com/LKHN/os-autoinst/actions/runs/4874753836/jobs/8696080601

2023-05-03 19:45 UTC, Martchus commented
Likely by just setting `bmwqemu::vars{ARCH} = 's390x';` before invoking the function you need to test. You can also delete keys/values from that global hash map if they lead to cases you don't want to test.

2023-05-05 15:50 UTC, LKHN commented
It looks like, it passes now but no response yet from the codecov -https://app.codecov.io/gh/os-autoinst/os-autoinst/commit/16e5a31424afd5f4dbfa2845c7be237d21aa9ad0

I tried to extend the unit tests to cover the testing of these QEMU options:

When: `ARCH => 's390x', QEMU_VIDEO_DEVICE => 'virtio-gpu', OFW => 0`

- EDID is present for virtio-gpu
- -boot option not present.
- virtio-keyboard is present.
- no audio options present.
- isa-fdc.fdtypeA=none is not present.
- virtio-rng is present.
- virtio-tablet is present.

What is left, is the testing of `virtio-scsi` as `SCSICONTROLLER` Which comes from `OpenQA/Qemu/Proc.pm`.

@Martchus @okurz  Could tell me if this approach of the implementation tests is correct? If yes how can I test the `SCSICONTROLLER` too?

2023-05-08 11:17 UTC, Martchus commented
> but no response yet from the codecov

The CI check shows your diff is fully covered. I think that's good enough.

2023-05-08 11:17 UTC, Martchus approved these changes

2023-05-08 11:54 UTC, LKHN commented on OpenQA/Qemu/Proc.pm
> +        my $is_s390x = $arch eq 's390x';
Updated. Many thanks!

2023-05-08 14:27 UTC, okurz approved these changes

2023-05-10 10:43 UTC, LKHN commented
@Martchus and @okurz , Thanks for the review, please let me know if we need any further changes.

2023-05-10 12:45 UTC, Martchus commented
No further changes are required. The PR hasn't been merged automatically because not all OBS checks have reported back. However, https://build.opensuse.org/package/show/devel:openQA:GitHub:os-autoinst:os-autoinst:PR-2309/os-autoinst shows that all builds were successful. So I'm merging this manually.

2023-05-10 12:46 UTC, merged