Suppress unneeded log output in 17-basetest.t
os-autoinst/os-autoinst pull request #2314
Opened 2023-05-11 17:08 UTC by mimi1vx

https://progress.opensuse.org/issues/128930

2023-05-11 19:11 UTC, perlpunk commented
I can still see the output though
https://github.com/os-autoinst/os-autoinst/actions/runs/4950600104/jobs/8854430796?pr=2314#step:3:617

2023-05-11 19:54 UTC, Martchus commented
> I can still see the output though

Yes. Depending on how these logging helpers are imported one likely needs to mock another module (e.g. that module where the functions are actually defined or the importing module).

2023-05-12 06:50 UTC, okurz requested changes
https://github.com/os-autoinst/os-autoinst/actions/runs/4953270962/jobs/8860573724?pr=2314#step:3:617 looks ok.

s/uneded/unneeded/ in the git commit message

2023-05-12 09:57 UTC, okurz approved these changes

2023-05-12 10:09 UTC, Martchus approved these changes

2023-05-12 10:09 UTC, perlpunk approved these changes

2023-05-12 10:09 UTC, merged