Provide network boot options for qemu
os-autoinst/os-autoinst pull request #2319
Opened 2023-05-31 10:34 UTC by b10n1k

With this PR I first enable the option to pass network boot with BOOTFROM. Qemu, however, provides `bootindex` property on the individual block or net devices. This property is more flexible from `-boot`, where some aarch do not support. For more read
https://www.qemu.org/docs/master/system/bootindex.html

I do not rethink and I did not refactor the entire logic, to prioritize `bootindex` for _devices_ or _drives_. I merely enable this option in a particular case (PXE) where the test requests to boot from network. As for now, when PXEBOOT is given, and only on x86_64, the test constructs the qemu command with `-boot n`. This option is not available on other archs like aarch4 where the net boot is not doable.

2023-05-31 11:24 UTC, Martchus reviewed
It would be great to extend unit tests. I'm also wondering whether this is worth mentioning in the documentation.

2023-06-06 03:53 UTC, okurz commented
+1

IMHO no further documentation changes are needed. doc/backend_vars.asciidoc mentions

```
BOOTFROM;chars;undef;Influences order of boot devices. See qemu -boot option
```

this pull request actually just adds what one might expect from supported qemu boot options that did not work in before

2023-06-06 09:59 UTC, Martchus commented on doc/backend_vars.asciidoc
> +PXEBOOT;boolean or 'once';0;Boot VM from network, on every boot or only once if set to 'once'. If value is 1 it sets `bootindex=N` for each network device.
Judging by the code this also applies to `once` (or any truthy value):
```suggestion
PXEBOOT;boolean or 'once';0;Boot VM from network, on every boot or only once if set to 'once'. If value is 1 or 'once' it sets `bootindex=N` for each network device.
```

2023-06-06 10:22 UTC, Martchus requested changes

2023-06-06 10:22 UTC, Martchus commented on t/18-backend-qemu.t
> +        $bootfrom_supported = ($arch eq 'x86_64') ? 0 : 1;
```suggestion
        $bootfrom_supported = $arch ne 'x86_64';
```

2023-06-06 10:22 UTC, Martchus commented on t/18-backend-qemu.t
> +        unlike $cmdline, $expected, '-boot option is ignored on aarch64';
```suggestion
        unlike $cmdline, $expected, "'-boot' option is ignored on $arch";
```

2023-06-06 11:14 UTC, Martchus approved these changes

2023-06-06 14:52 UTC, kalikiana approved these changes

2023-06-06 14:52 UTC, merged