Remove save_storage_drives from testapi
os-autoinst/os-autoinst pull request #2333
Opened 2023-06-23 09:47 UTC by mimi1vx

https://progress.opensuse.org/issues/130922

save_storage_drives never worked and ins't used by any test

2023-06-23 09:58 UTC, okurz requested changes
The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

Make sure that the git commit message subject line states the *Why* because that goes into the changelog. Think from the changelog reader perspective what you want to read there.

You can not know if this is used by any tests by any user of openQA. I guess you just grepped os-autoinst-distri-opensuse?

I am not convinced we should remove that function. I am sure it has worked in a certain way when it was introduced. Maybe we introduced a regression since then and our unit tests are of course not going deep enough to really cover the functionality.

Did you try to make use of it and try to fix it?

2023-06-23 10:01 UTC, mimi1vx commented
Nobody ever reported it’s wrong by design and it can’t work … so premise it isn’t used is with big probability correct

2023-06-23 10:53 UTC, foursixnine commented
> You can not know if this is used by any tests by any user of openQA. I guess you just grepped os-autoinst-distri-opensuse?
> 
> I am not convinced we should remove that function. I am sure it has worked in a certain way when it was introduced. Maybe we introduced a regression since then and our unit tests are of course not going deep enough to really cover the functionality.
> 
> Did you try to make use of it and try to fix it?

@mimi1vx how is it failing? Back when I introduced the function, it was meant for developers interested in getting both, a memory dump and a dump of the storage devices available for the SUT... I I have no attachments to the code, however I would suggest deprecating it first and removing it in the future.

Looking at the unit test, it's kind of snake-oily though... but the backend calls should _work_ otherwise we should have found about this long time ago.

2023-06-23 11:08 UTC, mimi1vx commented
> @mimi1vx how is it failing? Back when I introduced the function, it was meant for developers interested in getting both, a memory dump and a dump of the storage devices available for the SUT... I I have no attachments to the code, however I would suggest deprecating it first and removing it in the future.
> 

as I wrote in the commit message it can't work -> `qemu-img convert` doesn't work on attached images. And nobody newer used this function --> so nobody found its faulty.

2023-06-23 11:53 UTC, Martchus commented
Maybe this is intended to be called when the VM is not in a running state?

2023-06-23 14:59 UTC, okurz approved these changes
Ok for me then as well. I will leave it for @foursixnine to decide then how we should proceed

2023-06-26 09:24 UTC, foursixnine commented
> Then it really looks like we should remove this function. I'm only wondering why we ever thought this was working (and thus merged it).

The code changed after the Qemu rewrite, in any case  I'm also fine with removing it then too.

2023-06-26 09:24 UTC, foursixnine approved these changes

2023-06-26 09:25 UTC, merged

2023-06-26 09:25 UTC, foursixnine commented
Hell... I forgot about Mergify! my bad!