dist: Recommend more efficient encoder
os-autoinst/os-autoinst pull request #2346
Opened 2023-07-26 20:37 UTC by okurz

2023-07-26 20:38 UTC, perlpunk approved these changes

2023-07-27 08:54 UTC, Martchus requested changes

2023-07-27 09:09 UTC, okurz commented on dist/rpm/os-autoinst.spec
> +Recommends:     ffmpeg-4
err, right. Fun with this versioned package names :) I looked into https://build.opensuse.org/package/view_file/openSUSE:Factory/ffmpeg-6/ffmpeg-6.spec?expand=1 but could not find any sensible "Provides" that we could rely upon. Anybody has a good idea?

2023-07-27 10:08 UTC, Martchus commented on dist/rpm/os-autoinst.spec
> +Recommends:     ffmpeg-4
```suggestion
Recommends:     ffmpeg
```

2023-07-31 12:27 UTC, okurz commented on dist/rpm/os-autoinst.spec
> +Recommends:     ffmpeg-4
No, wrong operating system:

```
$ podman run --rm -it registry.opensuse.org/opensuse/leap:15.5
cb0c41737f7e:/ # zypper se --details ffmpeg
…

S | Name                         | Type    | Version                  | Arch   | Repository
--+------------------------------+---------+--------------------------+--------+----------------
  | cmus-plugin-ffmpeg           | package | 2.10.0-bp155.1.10        | x86_64 | Main Repository
  | ffmpeg                       | package | 3.4.2-150200.11.28.1     | x86_64 | Main Repository
  | ffmpeg-4                     | package | 4.4-150400.3.15.1        | x86_64 | Main Repository
```

2023-08-10 08:17 UTC, mimi1vx commented on dist/rpm/os-autoinst.spec
> +Recommends:     ffmpeg-4
more like something

2023-08-10 11:33 UTC, Martchus commented on dist/rpm/os-autoinst.spec
> +Recommends:     ffmpeg-4
Although we probably even wanted ffmpeg-6 or whatever is currently the latest.

2023-09-01 16:03 UTC, okurz commented on dist/rpm/os-autoinst.spec
> +Recommends:     ffmpeg-4
`Recommends:            ffmpeg >= 4` looks good, done

2023-09-04 15:44 UTC, kalikiana approved these changes

2023-09-11 14:00 UTC, okurz commented
@Martchus please re-evaluate

2023-09-11 14:59 UTC, Martchus approved these changes
I've just tested this in a Tumbleweed and Leap 15.5 container and it looks like this version constraint would really install the latest version each system provides (ffmpeg-6 or ffmpeg-4).

2023-09-11 14:59 UTC, merged