ssh_screen: Log SSH read errors
os-autoinst/os-autoinst pull request #2359
Opened 2023-09-13 08:49 UTC by mdoucha

OpenQA currently ignores all read errors on SSH channels which makes it difficult to tell apart network failures from plain SUT timeouts. Log each SSH error once into autoinst-log.txt for now. Depending on later analysis, we can turn most SSH read errors into fatal failures.

2023-09-13 09:02 UTC, mimi1vx approved these changes
some tests would be nice

2023-09-13 11:28 UTC, mdoucha commented
> some tests would be nice

Only if you add test coverage for the existing code first.

2023-09-13 11:39 UTC, mdoucha commented on consoles/ssh_screen.pm
> +        }
Changed.

2023-09-13 13:18 UTC, Martchus approved these changes

2023-09-14 05:42 UTC, okurz requested changes
See https://github.com/os-autoinst/os-autoinst/pull/2359/checks?check_run_id=16771776288

2023-09-14 06:57 UTC, grisu48 approved these changes
Nice, small, tidy and functional :+1:

2023-09-14 08:16 UTC, mdoucha commented
> See https://github.com/os-autoinst/os-autoinst/pull/2359/checks?check_run_id=16771776288

Fixed.

2023-09-14 08:56 UTC, okurz commented
blocked by https://github.com/os-autoinst/os-autoinst/pull/2360 now

2023-09-14 09:18 UTC, mdoucha commented
> blocked by #2360 now

You can merge this manually without fixing the deprecation warnings in unrelated code.

2023-09-25 11:04 UTC, merged