Create dir for gre up script before writing in os-autoinst-setup-multi-machine
os-autoinst/os-autoinst pull request #2385
Opened 2023-10-17 12:48 UTC by asdil12

Ticket: https://progress.opensuse.org/issues/133025

2023-10-17 12:50 UTC, okurz requested changes
Commit message too long. How about

"os-autoinst-setup-multi-machine: Fix missing dir for gre-up-script"

2023-10-17 13:31 UTC, kalikiana approved these changes

2023-10-17 13:33 UTC, Martchus approved these changes

2023-10-17 18:00 UTC, okurz approved these changes

2023-10-17 18:00 UTC, merged

2023-10-18 09:37 UTC, okurz commented
After thinking about this again: The directory should come from wicked. If it does not exist then that's simply because wicked is not installed. In our openQA-in-openQA tests we likely have Tumbleweed with NetworkManager, not wicked. Just saying.