openvswitch: Ensure a consistent MTU size compatible with GRE tunnels
os-autoinst/os-autoinst pull request #2409
Opened 2023-11-28 12:42 UTC by okurz

So far common multi-machine tests set an MTU size but not always consistently and we want to ensure we have a properly working setup without relying on test maintainers to know the setup of machines.

Related progress issue: https://progress.opensuse.org/issues/151310

2023-11-28 12:51 UTC, asdil12 requested changes

2023-11-28 12:53 UTC, Martchus commented on script/os-autoinst-setup-multi-machine
> +    ovs-vsctl set int $bridge mtu_request=1450
We just tried with 1450 and it might have helped. I suppose we should wait until we have gathered more experience until we merge this PR.

2023-11-28 12:55 UTC, okurz commented on script/os-autoinst-setup-multi-machine
> +    ovs-vsctl set int $bridge mtu_request=1450
@nicksinger can you help me there?

2023-11-30 19:13 UTC, sqozz commented on script/os-autoinst-setup-multi-machine
> +    ovs-vsctl set int $bridge mtu_request=1450
It was honestly just a blind guess based on what is written on https://docs.openvswitch.org/en/latest/faq/issues/:

> Sometimes this behavior is not desirable, for example with tunnels. The MTU of an internal interface can be explicitly set using the following command:
> 
> $ ovs-vsctl set int br0 mtu_request=1450

maybe we could use that as reference. OTOH we have it mentioned in the issue anyway.

2023-11-30 19:14 UTC, nicksinger commented on script/os-autoinst-setup-multi-machine
> +    ovs-vsctl set int $bridge mtu_request=1450
It was honestly just a blind guess based on what is written on https://docs.openvswitch.org/en/latest/faq/issues/:

> Sometimes this behavior is not desirable, for example with tunnels. The MTU of an internal interface can be explicitly set using the following command:
> 
> $ ovs-vsctl set int br0 mtu_request=1450

maybe we could use that as reference. OTOH we have it mentioned in the issue anyway.

2023-12-01 10:49 UTC, mimi1vx approved these changes

2023-12-01 10:50 UTC, merged