Hide unvanted debug message in t/08-autotest.t
os-autoinst/os-autoinst pull request #2426
Opened 2024-01-08 11:19 UTC by mimi1vx

2024-01-10 10:24 UTC, okurz requested changes

2024-01-10 10:24 UTC, okurz commented on t/08-autotest.t
> +    is $msg[0], 'scheduling pythontest_with_bad_run_fn tests/pythontest_with_bad_run_fn.py', "debug message from autotest";
```suggestion
    is $msg[0], 'scheduling pythontest_with_bad_run_fn tests/pythontest_with_bad_run_fn.py', 'debug message from autotest';
```

2024-01-10 14:49 UTC, Martchus approved these changes

2024-01-11 06:25 UTC, okurz approved these changes

2024-01-11 06:26 UTC, merged