Mention possibility to run `isotovideo` in a CI runner
os-autoinst/os-autoinst pull request #2503
Opened 2024-06-13 14:03 UTC by Martchus

See https://progress.opensuse.org/issues/159399

2024-06-13 14:18 UTC, okurz requested changes

2024-06-13 14:31 UTC, Martchus commented on README.asciidoc
> +also contains further details.
No, those are wrapped at a higher limit. I converted the whole document to 80 characters. (Some paragraphs were even wrapped before 80 characters. There was no consistency at all.)

2024-06-13 20:50 UTC, kalikiana approved these changes

2024-06-14 07:33 UTC, okurz approved these changes

2024-06-14 07:49 UTC, merged