[WIP] Save ipmi sol output as log file
os-autoinst/os-autoinst pull request #2504
Opened 2024-06-14 10:26 UTC by waynechen55

IPMI SOL console output records important information about system under test, including boot-up process, error messages, unexpected abnormal output and etc, detailed texts of which likely might not be recorded by screenshot or even video clip. By saving full output of ipmi sol console to a log file, which will be uploaded at the end of test run, investigation and examination work can be executed much more easily and conveniently without losing any information.

2024-06-19 05:44 UTC, waynechen55 commented
@alice-suse @guoxuguang @Julie-CAO @RoyCai7 @nanzhg @tbaev Please have a look.

2024-06-19 08:15 UTC, Martchus reviewed
I assume you have tested this manually. It would make sense to document the new variable.

2024-06-19 08:26 UTC, waynechen55 commented
> I assume you have tested this manually. It would make sense to document the new variable.

Add entry for setting IPMISOL_LOG in doc/backend_vars.asciidoc.

2024-06-19 13:32 UTC, Martchus requested changes

2024-06-19 13:32 UTC, Martchus commented on doc/backend_vars.asciidoc
> +IPMISOL_LOG;boolean;1;Record IPMI SOL output into ipmisol-log in consoles/sshXtermIPMI.pm, disabled by default
For the sake of consistency:
```suggestion
IPMI_SOL_LOG;boolean;1;Record IPMI SOL output into ipmisol-log in consoles/sshXtermIPMI.pm, disabled by default
```

2024-06-19 13:32 UTC, Martchus commented on consoles/sshXtermIPMI.pm
> +    push(@command, qw(2>&1 | tee -a ipmisol-log)) if $bmwqemu::vars{IPMISOL_LOG};
```suggestion
    push(@command, qw(2>&1 | tee -a ipmisol-log)) if $bmwqemu::vars{IPMI_SOL_LOG};
```

2024-06-19 13:32 UTC, Martchus commented
Thanks, I only have a minor nitpick.

2024-06-20 02:36 UTC, alice-suse commented
Very good supplemental log for bare metal test. The log is well readable for text logs, while for text graphic, eg grub2 menu or autoyast installation process, the output is not easy to interpret directly. It will be good to find some tool to interpret that part, but it is a different story, the PR code is good to merge, IMO.

2024-06-20 02:37 UTC, alice-suse commented
@mdoucha @czerw Maybe you are interested?

2024-06-20 02:59 UTC, waynechen55 commented on doc/backend_vars.asciidoc
> +IPMISOL_LOG;boolean;1;Record IPMI SOL output into ipmisol-log in consoles/sshXtermIPMI.pm, disabled by default
Done

2024-06-20 03:00 UTC, waynechen55 commented on consoles/sshXtermIPMI.pm
> +    push(@command, qw(2>&1 | tee -a ipmisol-log)) if $bmwqemu::vars{IPMISOL_LOG};
Done

2024-06-20 03:55 UTC, Julie-CAO commented
This enhancement is very helpful for test review! thank you.

2024-06-20 06:07 UTC, czerw commented
Why? We have already....
![Screenshot from 2024-06-20 06-06-20](https://github.com/os-autoinst/os-autoinst/assets/28350037/4f0de202-fd68-45da-baa6-0d1f15a5b1f4)

2024-06-20 06:38 UTC, waynechen55 commented
> Why? We have already.... ![Screenshot from 2024-06-20 06-06-20](https://private-user-images.githubusercontent.com/28350037/341290109-4f0de202-fd68-45da-baa6-0d1f15a5b1f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjU3MjgsIm5iZiI6MTcxODg2NTQyOCwicGF0aCI6Ii8yODM1MDAzNy8zNDEyOTAxMDktNGYwZGUyMDItZmQ2OC00NWRhLWJhYTYtMGQxZjE1YTViMWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA2MzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5N2Q3ZmNlNTBiZjU0OTEyZWYxNTM0ZTA0M2UxNDA2ZTRhNTkwODc1ZWVkY2ZjOGFjYzdhMjQ2NDM4YmFiNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4820SJ9Q4b7M_v4wjQ60WpH0I8gTWj4aw00AYIi4Mgw)
> 
> Introduced in 2021 #1881

I suggest remove ```HARDWARE_CONSOLE_LOG``` and keep ```IPMI_SOL_LOG``` if they are the same thing.

2024-06-20 07:18 UTC, waynechen55 commented
> Why? We have already.... ![Screenshot from 2024-06-20 06-06-20](https://private-user-images.githubusercontent.com/28350037/341290109-4f0de202-fd68-45da-baa6-0d1f15a5b1f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4Njc5OTMsIm5iZiI6MTcxODg2NzY5MywicGF0aCI6Ii8yODM1MDAzNy8zNDEyOTAxMDktNGYwZGUyMDItZmQ2OC00NWRhLWJhYTYtMGQxZjE1YTViMWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA3MTQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NmFlNzFlZTFkZjc4Y2RhOWRiN2VhNzlmNjBjOTc3NjI0MTM1ODkwZjk2ZDdhNjA4Mzk2YzA2MWYzZDkzM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PoXoiCaKrXZDwKGiVH3UpUPs0e97QBlEbN5KMy_EjYs)
> 
> Introduced in 2021 #1881

I tried running test with ```HARDWARE_CONSOLE_LOG=1``` which uploads similar log to ```uploaded log``` section instead of ```result files```. Please refer to this [test run with HARDWARE_CONSOLE_LOG=1 link1](http://10.67.18.153/tests/2857) [link2](http://10.100.228.134/tests/2857) [link3](http://10.100.204.18/tests/2857) [link4](http://10.149.193.170/tests/2857).

2024-06-20 07:25 UTC, czerw commented
I can't access any VR link on http://10.67.18.153/ and I'm in company VPN as usual.

2024-06-20 07:26 UTC, waynechen55 commented
> I can't access any VR link on http://10.67.18.153/ and I'm in company VPN as usual.

Use link2. Try another link if you can not access either of them.

2024-06-20 07:29 UTC, czerw commented
> Use link2. Try another link if you can not access either of them.

This one works for me http://10.100.228.134/tests/2857/logfile?filename=hardware-console-log.txt  and we can see `HARDWARE_CONSOLE_LOG` works for you.

2024-06-20 07:30 UTC, waynechen55 commented
> > Use link2. Try another link if you can not access either of them.
> 
> This one works for me http://10.100.228.134/tests/2857/logfile?filename=hardware-console-log.txt and we can see `HARDWARE_CONSOLE_LOG` works for you.

* First it is not in ```Result files``` section.
* Second I think it would be better to rename it to ```IPMI_SOL_LOG``` ???

2024-06-20 07:34 UTC, czerw commented
> * First it is not in `Result files` section.

I don't see it as problem at all.

> * Second I think it would be better to rename it to `IPMI_SOL_LOG` ???

We need more generic name. It works also for other backends spvm, hmc (which don't use sol).

2024-06-20 07:35 UTC, waynechen55 commented
> > * First it is not in `Result files` section.
> 
> I don't see it as problem at all.
> 
> > * Second I think it would be better to rename it to `IPMI_SOL_LOG` ???
> 
> We need more generic name. It works also for other backends spvm, hmc (which don't use sol).

If this is the case, I think ```HARDWARE_CONSOLE_LOG``` can also be adopted by us.

2024-06-20 08:10 UTC, okurz requested changes
waiting for clarification on https://github.com/os-autoinst/os-autoinst/pull/2504#issuecomment-2180015212

2024-06-20 08:23 UTC, waynechen55 commented
> waiting for clarification on [#2504 (comment)](https://github.com/os-autoinst/os-autoinst/pull/2504#issuecomment-2180015212)

What to be clarified ?

2024-06-20 10:37 UTC, okurz commented
> > waiting for clarification on [#2504 (comment)](https://github.com/os-autoinst/os-autoinst/pull/2504#issuecomment-2180015212)
> 
> What to be clarified ?

If you can just use the existing feature and close this PR unmerged, need to adapt the existing feature and update this PR or need this PR with the additional feature

2024-06-21 02:28 UTC, waynechen55 commented
> > > waiting for clarification on [#2504 (comment)](https://github.com/os-autoinst/os-autoinst/pull/2504#issuecomment-2180015212)
> > 
> > 
> > What to be clarified ?
> 
> If you can just use the existing feature and close this PR unmerged, need to adapt the existing feature and update this PR or need this PR with the additional feature

I think we can use existing feature.

2024-06-21 06:59 UTC, okurz commented
as per https://github.com/os-autoinst/os-autoinst/pull/2504#issuecomment-2181864092

2024-06-21 06:59 UTC, closed without merging