Exclude sub packages with many additional dependencies on SLE
os-autoinst/os-autoinst pull request #2545
Opened 2024-09-12 13:53 UTC by Martchus

As stated in https://build.suse.de/request/show/343857#comment-4023273 not all sub packages are installable on SLE. This only concerns the `devel` and `deps` sub packages which are really optional. So it makes sense to avoid submitting a huge number of Haskell some utility packages to SLE and exclude those packages instead.

Related ticket: https://progress.opensuse.org/issues/165683

2024-09-12 13:58 UTC, okurz requested changes
I would like to resolve the open points in https://github.com/os-autoinst/openQA/pull/5923 first

2024-09-12 14:09 UTC, Martchus commented
Maybe we can keep the `-deps` packages, see https://progress.opensuse.org/issues/165683#note-29.

2024-09-13 15:03 UTC, okurz approved these changes
Either way the change is fine

2024-09-13 16:28 UTC, kalikiana approved these changes

2024-09-13 16:28 UTC, merged