Full test coverage for script/dewebsockify
os-autoinst/os-autoinst pull request #2598
Opened 2024-12-18 17:09 UTC by r-richardson

This PR turns the script/dewebsockify into a Modulino, and fully covers the script by tests. (WIP)

2024-12-18 19:16 UTC, Martchus requested changes
I think it is ok to rename this to `dewebsockify.pm` but the file should then be moved out of `script` and live where other modules live (probably `OpenQA/Isotovideo/…`). There would still be `script/dewebsockify` but it would simply use that module. This way we could also avoid the `main(parse_args()) if not caller();` line and by avoiding the renaming you also avoid further changes that would be necessary.

2024-12-18 19:16 UTC, Martchus commented on t/39-dewebsockify.t
> +}
Maybe it is possible to simply use a Mojo log object here (created via `Mojo::Log->new`).

2024-12-19 10:35 UTC, okurz commented on script/dewebsockify
> +use warnings;
why change that?

2024-12-19 10:37 UTC, okurz commented on t/27-consoles-vmware.t
> +    my $dewebsockify_cmd_start = "$bmwqemu::topdir/script/dewebsockify.pm --listenport $tcp_port --websocketurl";
don't call a module like a script. Either import the module and call functions within or call the original script

2024-12-19 14:07 UTC, perlpunk commented on OpenQA/Isotovideo/dewebsockify.pm
> +main(parse_args()) if not caller();
This should be in the script itself.
The way it is now is kind of hidden, and also it doesn't work because caller will always return something true.

2024-12-19 14:11 UTC, perlpunk requested changes

2024-12-19 14:11 UTC, perlpunk commented on t/27-consoles-vmware.t
> +        system "'$bmwqemu::topdir/script/dewebsockify.pm' --listenport '$port' --websocketurl '$wss_url' --cookie 'vmware_client=VMware; $session' --insecure"; # uncoverable statement
We should not call a module directly as a script.

2025-01-02 10:22 UTC, okurz requested changes

2025-01-02 10:22 UTC, okurz commented on t/39-dewebsockify.t
> +$mock_stream->mock(close_gracefully => sub { });
chaining should work

```suggestion
$mock_stream->redefine(new => sub { bless {}, 'Mojo::IOLoop::Stream' })->redefine(start => sub { })->redefine(on => sub { })->redefine(close_gracefully => sub { });
```

probably even the following works


```suggestion
$mock_stream->redefine(new => bless {}, 'Mojo::IOLoop::Stream')->redefine(start => undef)->redefine(on => undef)->redefine(close_gracefully => undef);
```

2025-01-02 16:03 UTC, Wabri requested changes

2025-01-02 16:03 UTC, Wabri commented on OpenQA/Isotovideo/Dewebsockify.pm
> +                    else {
```suggestion
                    } else {
```

2025-01-02 16:03 UTC, Wabri commented on t/39-dewebsockify.t
> +        }
```suggestion
        $accept_callback = $cb if ($event eq 'accept'); # saving callback for reusing later
```

2025-01-08 10:25 UTC, okurz commented on t/27-consoles-vmware.t
> +        my $dewebsockify_pid = open(my $dewebsockify_pipe, "$dewebsockify_cmd_start ws://127.0.0.:4 2>&1 |") or die "Unable to start dewebsockify: $!";
On purpose it's not correct :)

2025-01-08 10:26 UTC, okurz commented on t/39-dewebsockify.t
> +# Copyright 2019-2024 SUSE LLC
```suggestion
# Copyright SUSE LLC
```

2025-01-08 11:43 UTC, r-richardson commented on t/27-consoles-vmware.t
> +        my $dewebsockify_pid = open(my $dewebsockify_pipe, "$dewebsockify_cmd_start ws://127.0.0.:4 2>&1 |") or die "Unable to start dewebsockify: $!";
yes, this is supposed to trigger an error anyway, but i had to break the URL further as if one is having a reverse proxy running in the BG and only supplying localhost with port 0 would cause the client to be accepted and therefore the test would not fail as expected.

2025-01-08 11:44 UTC, r-richardson commented on OpenQA/Isotovideo/Dewebsockify.pm
> +                        $tx->max_websocket_size(1024**3);    # required to avoid 1009 error, at least when using raw encoding
Yes i'm pretty sure thats it :+1:  (although i havent written this code, only moved it from the original `script/dewebsockify`)

2025-01-08 12:49 UTC, Wabri commented on t/27-consoles-vmware.t
> +        my $dewebsockify_pid = open(my $dewebsockify_pipe, "$dewebsockify_cmd_start ws://127.0.0.:4 2>&1 |") or die "Unable to start dewebsockify: $!";
Oh yes, you are both right. sorry :pray:

2025-01-09 12:45 UTC, Martchus commented on t/39-dewebsockify.t
> +    package MockReq;
It would be cleaner to have separate `{ }` blocks for the different packages.

2025-01-10 08:56 UTC, okurz commented on OpenQA/Isotovideo/Dewebsockify.pm
> +    die "Arguments must be a hash reference\n" unless defined $args && ref($args) eq 'HASH';
The "\n" would mean one wouldn't see where this die would be triggered. is that intended?

2025-01-10 08:56 UTC, okurz commented on script/dewebsockify
> -    example: --websocketurl wss://... --listenport 590x --cookie "vmware_client=VMware; some_session=foobar" --insecure';
I would keep those two lines. You can include in below in the usage string

2025-01-10 09:28 UTC, r-richardson commented on OpenQA/Isotovideo/Dewebsockify.pm
> +    die "Arguments must be a hash reference\n" unless defined $args && ref($args) eq 'HASH';
hmm, i had added that line for debugging and thought it'd maybe make sense to keep anyways, but you're right the \n does not make sense here. I'll remove it.

2025-01-10 10:24 UTC, perlpunk commented on t/39-dewebsockify.t
> +    package MockTxGeneric;
Can you try the suggestion from the meeting? It's a bit shorter
```suggestion
package MockTxGeneric {
```

2025-01-10 10:39 UTC, perlpunk commented on t/39-dewebsockify.t
> +    use Test::Most;
Why is this necessary here? It's already used at the top of this file

2025-01-10 10:42 UTC, perlpunk commented on t/39-dewebsockify.t
> +}
Just for completeness, this would be an alternative:
```suggestion
sub MockTxFailNoCodeReq::cookies { }
sub MockTxFailNoCodeReq::headers { bless {}, 'MockTxFailNoCodeHeaders' }
```

2025-01-10 11:29 UTC, Martchus commented on OpenQA/Isotovideo/Dewebsockify.pm
> +            if (!$ws_connection) {
This code was only moved. Splitting it into a separate function would be nice but I'd accept the PR as-is. If this function is split, it should be split in a separate commit.

2025-01-10 11:30 UTC, Martchus commented on t/39-dewebsockify.t
> +    use Test::Most;
Yes, probably just a leftover to be removed.

2025-01-10 14:54 UTC, okurz commented
@r-richardson I see that you incorporated the last comments one by one but the PR is still in draft and codecov reports incomplete coverage and there are older still open comments. What is your general plan?

2025-01-12 22:34 UTC, r-richardson commented on t/39-dewebsockify.t
> +}
I thought about that, it should work, but wouldnt that create unnecessary log files as a side effect and/or make it more complicated/less deterministic ?

2025-01-13 07:06 UTC, okurz commented
Anyone understands why https://app.codecov.io/gh/os-autoinst/os-autoinst/pull/2598?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=os-autoinst#4f6028807d537007150cd9d05454b07a-R58 is reported with missing coverage? @r-richardson can you reproduce that locally with Devel::Cover?

2025-01-13 09:51 UTC, perlpunk commented on t/39-dewebsockify.t
> +    package MockTxGeneric;
I don't see you tried it. Have you tried it and it didn't work?

2025-01-13 09:54 UTC, perlpunk commented
> Anyone understands why https://app.codecov.io/gh/os-autoinst/os-autoinst/pull/2598?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=os-autoinst#4f6028807d537007150cd9d05454b07a-R58 is reported with missing coverage? @r-richardson can you reproduce that locally with Devel::Cover?

It needs to be `#uncoverable statement`, not `#uncoverable line`.
But I would really prefer if @r-richardson tried out https://github.com/os-autoinst/os-autoinst/pull/2598#discussion_r1910160072 first to see if it makes a difference in coverage, and also to make things shorter.

btw, it seems that only the first ``package` line in a block isn't covered. So the uncoverable only needs to be added to the first. But please first try out my suggestion.

2025-01-13 10:56 UTC, r-richardson commented
> > Anyone understands why https://app.codecov.io/gh/os-autoinst/os-autoinst/pull/2598?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=os-autoinst#4f6028807d537007150cd9d05454b07a-R58 is reported with missing coverage? @r-richardson can you reproduce that locally with Devel::Cover?
> 
> It needs to be `#uncoverable statement`, not `#uncoverable line`. But I would really prefer if @r-richardson tried out [#2598 (comment)](https://github.com/os-autoinst/os-autoinst/pull/2598#discussion_r1910160072) first to see if it makes a difference in coverage, and also to make things shorter.
> 
> btw, it seems that only the first ``package` line in a block isn't covered. So the uncoverable only needs to be added to the first. But please first try out my suggestion.

I've tried a couple of variations of your suggestion yesterday though sadly it did also show up as uncovered.

<details>
  <summary>coverage screenshot</summary>

![Screenshot From 2025-01-13 11-53-25](https://github.com/user-attachments/assets/93830a01-8b6f-4fdc-8a9d-a003a956ed2c)

</details>

2025-01-13 14:07 UTC, Wabri requested changes
Couple of small "typos", but overall huge work :1st_place_medal:

2025-01-13 14:07 UTC, Wabri commented on OpenQA/Isotovideo/Dewebsockify.pm
> +sub main ($args) {
As @Martchus already commented [here](https://github.com/os-autoinst/os-autoinst/pull/2598/files#r1910244275), separate function would be nice, but not in the context of this pr. @okurz in those case we open a new task in progress?

2025-01-13 14:07 UTC, Wabri commented on t/39-dewebsockify.t
> +
```suggestion
```

2025-01-13 14:07 UTC, Wabri commented on t/39-dewebsockify.t
> +
```suggestion
```

2025-01-13 14:34 UTC, Martchus approved these changes

2025-01-13 15:16 UTC, perlpunk commented on t/39-dewebsockify.t
> +    package MockTxGenericReq;    # uncoverable statement
The packages don't all need their own block.
They wouldn't even need a block at all, but it's nicer for readability.
So I suggest to just use one block.
And then only the first `package` line needs `# uncoverable statement`

2025-01-13 15:45 UTC, okurz commented on OpenQA/Isotovideo/Dewebsockify.pm
> +sub main ($args) {
yes, good idea. please do that

2025-01-13 15:54 UTC, perlpunk commented on script/dewebsockify
> +OpenQA::Isotovideo::Dewebsockify::main(parse_args()) unless caller();
Just mentioning: since you moved the code to a real module, this trick to be able to unit test certain functions in a script is not necessary.
It won't hurt to keep that line.

2025-01-13 17:47 UTC, Wabri commented on OpenQA/Isotovideo/Dewebsockify.pm
> +sub main ($args) {
https://progress.opensuse.org/issues/175335

2025-01-14 07:49 UTC, okurz approved these changes

2025-01-14 12:05 UTC, Wabri approved these changes

2025-01-15 00:06 UTC, r-richardson commented on t/27-consoles-vmware.t
> +        system "'$bmwqemu::topdir/script/dewebsockify.pm' --listenport '$port' --websocketurl '$wss_url' --cookie 'vmware_client=VMware; $session' --insecure"; # uncoverable statement
I've reverted this line in the mean time, as the script is now still callable.

2025-01-15 00:08 UTC, r-richardson commented on t/39-dewebsockify.t
> +    package MockTxGeneric;
Have you seen [my comment](https://github.com/os-autoinst/os-autoinst/pull/2598#issuecomment-2586787234) below ? Sorry, i should've commented here or @ mention you

2025-01-16 15:21 UTC, merged