Modify loadtestdir in autotest for more code coverage
os-autoinst/os-autoinst pull request #2601
Opened 2024-12-24 05:20 UTC by gauravpathak

2024-12-24 14:43 UTC, okurz approved these changes

2024-12-24 15:18 UTC, Wabri requested changes

2024-12-24 15:18 UTC, Wabri commented on t/08-autotest.t
> +
Just to be sure that loadtestdir have load the directory we should check if the package variable `tests` contains one of the script in the directory, for example `boot.pm` the loadtest subroutine should create a `tests-boot` element
```suggestion
ok exists $autotest::tests{'tests-boot'}, 'boot.pm loaded';
```

If you want to check the content of the `tests` variable there is [`Data::Dumper`](https://metacpan.org/pod/Data::Dumper) module that can be use to translate data structures into string.

2024-12-24 21:58 UTC, okurz commented on autotest.pm
>  sub handle_sigterm ($sig) {    # uncoverable statement
That's not enough. One still needs to add uncoverable statement to every statement

2025-01-02 16:23 UTC, Wabri approved these changes

2025-01-02 16:23 UTC, Wabri commented
Please rebase!

2025-01-06 09:33 UTC, kalikiana commented
@mergifyio rebase

2025-01-06 09:55 UTC, merged

2025-01-06 11:15 UTC, perlpunk commented on t/08-autotest.t
> +    use lib 't/data/tests';
This is something that shouldn't be necessary. autotest should add the necessary include paths itself.
It seems to me `loadtestdir` hasn't been used for many years, not in our code and not in osado.
The way it works produces warnings, and below you are just kind of ignoring the warnings by comparing it to `ARRAY`, which is just a stringification of an array ref.
The warning is
```
loadtest needs a script below t/data/tests - t/data/tests/tests/assert_screen.pm is not 
```
That's because of the way `loadtestdir` passes the tests to `loadtest`.

I think we should rather fix `loadtestdir` instead, or remove it.

2025-01-06 11:16 UTC, perlpunk commented
What's the corresponding issue for this PR?

2025-01-07 10:27 UTC, gauravpathak commented on t/08-autotest.t
> +    use lib 't/data/tests';
So, Should we remove `loadtestdir` completely?

2025-01-07 11:07 UTC, perlpunk commented on t/08-autotest.t
> +    use lib 't/data/tests';
https://github.com/search?q=loadtestdir+language%3APerl&type=code&l=Perl
maybe not...
The problematic part seems to be that the `glob()` in `loadtestdir` can return a part of the path that is already in CASEDIR, and then `find_script` will complain about `(!-f join('/', $casedir, $script)`.

2025-01-08 09:01 UTC, gauravpathak commented on t/08-autotest.t
> +    use lib 't/data/tests';
I made a few changes. First, I attempted to check for the warning `loadtest needs a script below` instead of using `qr/ARRAY/`. However, I was still getting the following output:
```
# Subtest: loadtestdir
    not ok 1 - script found

    #   Failed test 'script found'
    #   at t/08-autotest.t line 456.
    #                   'ARRAY(0x55c13921d970)'
    #     doesn't match '(?^u:loadtest needs a script below)'
    ok 2 - loadscript success
    ok 3 - boot.pm loaded
    1..3
    # Looks like you failed 1 test of 3.
```

Additionally, to avoid using `use lib 't/data/tests';`, I had to set the casedir as follows:
`$bmwqemu::vars{CASEDIR} = Cwd::getcwd();`

I also provided the path to the tests directory when calling `loadtestdir`. Here’s the updated test code snippet:

```
subtest loadtestdir => sub {
    $bmwqemu::vars{CASEDIR} = Cwd::getcwd();
    stderr_like {
        like warning {
            autotest::loadtestdir('t/data/tests/tests');
        }, qr/loadtest needs a script below/, 'script found';
    } qr/scheduling/, 'loadscript success';
    ok exists $autotest::tests{'tests-boot'}, 'boot.pm loaded';
};
```
Could you please confirm if we can use the above test code snippet for `loadtestdir`?

2025-01-08 11:27 UTC, gauravpathak commented on t/08-autotest.t
> +    use lib 't/data/tests';
Tried some more changes, the catch is in the way casedir is set. If I use below code where I use relative path of current dir as casedir, then it doesn't throw the warning

```
subtest loadtestdir => sub {
    $bmwqemu::vars{CASEDIR} = '.';
    stderr_like {
        autotest::loadtestdir('t/data/tests/tests');
    } qr/scheduling/, 'loadscript success';
    ok exists $autotest::tests{'tests-boot'}, 'boot.pm loaded';
};
```