Cover code of os-autoinst path needle.pm fully
os-autoinst/os-autoinst pull request #2603
Opened 2024-12-24 16:29 UTC by Wabri

https://progress.opensuse.org/issues/167932

2025-01-09 09:42 UTC, perlpunk commented on needle.pm
> +
```suggestion
```

2025-01-09 09:50 UTC, perlpunk commented on t/misc_needles/test_tag1.json
> +{
Could those needles be a bit more minimalized, e.g. remove things like clickpoint and other stuff that's not important for the actual test?

2025-01-09 09:55 UTC, perlpunk requested changes
It's ok to have separate commits to make several changes more comprehensible, but this is a bit too detailed, and also
* there are commits updating previous code, those should be squashed
* some commits have a title that conflicts with the actual diff

2025-01-09 11:30 UTC, perlpunk commented on needle.pm
> +        bmwqemu::diag("$self->{name} contains $g twice"), next if ($check_dups{$g});
Have you tried to cover this?
If something is not too difficult to cover, we should do it. The ideal goal is to have 100% coverage, not to appear every line as covered although it really isn't.
I know I disagree with @okurz here but I think we shouln't overuse this one-line trick.

2025-01-09 12:29 UTC, Wabri commented
Fix incoming :+1: 

![image](https://github.com/user-attachments/assets/5af6c3e6-d835-4847-b03a-ee1bba77f230)

2025-01-09 13:15 UTC, Martchus requested changes
Looks like the PNG images you're adding here actually contain JSON data. That's confusing. The the PNG images doesn't need to be valid you can just add empty files or a minimal PNG or a symlink to some other PNG we already have in this repo.

2025-01-09 13:15 UTC, Martchus commented on needle.pm
> +        bmwqemu::diag("$self->{name} contains $g twice"), next if ($check_dups{$g});
And I must also say that using the comma operator like this is probably not a good idea as it makes the code less readable (and is it even correct?).

2025-01-09 13:15 UTC, Martchus commented on needle.pm
> -sub save ($self, $fn = $self->{file}) {
Are you removing this function because it is unused? I'm wondering whether this function is really completely useless (e.g. it might be useful during development/debugging) but I'm also not against removing it (as the function is not very well written anyway).

2025-01-09 14:40 UTC, perlpunk commented on needle.pm
> -sub save ($self, $fn = $self->{file}) {
See https://progress.opensuse.org/issues/167932#note-11 where I investigated if the function is used.
Note that it already got a bug 5 years ago.

When you say "useful during development/debugging", what do you mean by that? During openQA development, or during developing an test openQA test? When and how would you use it?

2025-01-09 15:32 UTC, Martchus commented on needle.pm
> -sub save ($self, $fn = $self->{file}) {
During development of os-autoinst itself to dump a needle for debuging purposes. But as I said, I'm fine with removing the function.

2025-01-10 09:23 UTC, Wabri reviewed
@Martchus I've done a copy paste of https://github.com/os-autoinst/os-autoinst/blob/master/t/misc_needles/click-point.png so it is already a symlink, but anyway it points to the json file

2025-01-10 09:23 UTC, Wabri commented on needle.pm
> +    warn "Can't find $self->{png}" and return unless -e $self->{png};
```
    -e: Checks if the file exists.
    -s: Checks if the file is non-empty.
```

Since the warning is for file not found I've updated with a check of the existing file

2025-01-10 11:00 UTC, perlpunk commented on t/01-test_needle.t
> +    sysopen(my $fh, $filename, O_WRONLY | O_CREAT, 0777) or die "Cannot create file '$filename': $!"; close($fh);
Why are you using sysopen here and not just a normal open?

2025-01-10 11:06 UTC, Wabri commented on t/01-test_needle.t
> +    sysopen(my $fh, $filename, O_WRONLY | O_CREAT, 0777) or die "Cannot create file '$filename': $!"; close($fh);
No real reason, I've just found out that method to create a new file. Do you think something like this could be better?
```suggestion
    open(my $fh, '>', $tag_png_path) or die "Cannot open file '$tag_png_path': $!"; close($fh);
```

2025-01-10 11:20 UTC, perlpunk commented on t/01-test_needle.t
> +    sysopen(my $fh, $filename, O_WRONLY | O_CREAT, 0777) or die "Cannot create file '$filename': $!"; close($fh);
Or just use
```
$filename->spew('');
```
You are using that for the json file, so why not for the png file as well

2025-01-10 11:21 UTC, perlpunk commented on needle.pm
> +    warn "Can't find $self->{png}" and return unless -e $self->{png};
That changes the behaviour, and maybe it is good to check for a non-empty file though. Maybe the warning should be updated to reflect that instead.

2025-01-10 11:25 UTC, Wabri commented on t/01-test_needle.t
> +    sysopen(my $fh, $filename, O_WRONLY | O_CREAT, 0777) or die "Cannot create file '$filename': $!"; close($fh);
I thought that works only for json encoding, but the subroutine takes string so make sense to just use also to create file

2025-01-10 11:33 UTC, perlpunk reviewed
Added some more simplifications

2025-01-10 11:33 UTC, perlpunk commented on t/01-test_needle.t
> +    path($tag_json_path)->spew('{"area": [{"x" : 123, "y" : 456}],"tags": ["tag1", "tag1"]}');
```suggestion
    path($sandbox, 'tag.png')->spew('');

    $tag_json_path->spew('{"area": [{"x" : 123, "y" : 456}],"tags": ["tag1", "tag1"]}');
```

2025-01-10 11:33 UTC, perlpunk commented on t/01-test_needle.t
> +    path($invalid_click_point_json_path)->spew('{"area": [{"click_point": "invalid"}]}');
```suggestion
    $invalid_click_point_json_path->spew('{"area": [{"click_point": "invalid"}]}');
```

2025-01-10 11:33 UTC, perlpunk commented on t/01-test_needle.t
> +            is($needle, undef, 'needle object not created with invalid click point');
```suggestion
            is $needle, undef, 'needle object not created with invalid click point';
```

2025-01-10 11:33 UTC, perlpunk commented on t/01-test_needle.t
> +    }
```suggestion
    $_->register() for needle::all();
```

2025-01-10 11:33 UTC, perlpunk commented on t/01-test_needle.t
> +    is(scalar @$result, 2, "two needles found for tag1");
```suggestion
    is scalar @$result, 2, "two needles found for tag1";
```

2025-01-10 11:33 UTC, perlpunk commented on t/01-test_needle.t
> +    is(scalar @$result, 2, "two needles found for tag2");
```suggestion
    is scalar @$result, 2, "two needles found for tag2";
```

2025-01-10 11:33 UTC, perlpunk commented on t/01-test_needle.t
> +    is(scalar @$result, 1, "one needle found for tag3");
```suggestion
    is scalar @$result, 1, "one needle found for tag3";
```

2025-01-10 11:33 UTC, perlpunk commented on t/01-test_needle.t
> +    is(scalar @$result, 0, "no needles found for nonexistent tag");
```suggestion
    is scalar @$result, 0, "no needles found for nonexistent tag";
```

2025-01-10 11:33 UTC, perlpunk commented on t/01-test_needle.t
> +    needle->new('test_tag3.json');
```suggestion
    needle->new($_) for qw(test_tag1.json test_tag2.json test_tag3.json);
```

2025-01-10 11:33 UTC, perlpunk commented on t/01-test_needle.t
> +    path($broken_json_path)->spew('{ "tags": ["test');
```suggestion
    $broken_json_path->spew('{ "tags": ["test');
```

2025-01-10 11:33 UTC, Wabri commented on needle.pm
> +    warn "Can't find $self->{png}" and return unless -e $self->{png};
Using -s will break the handle tags duplicates, but I'll populate the tag.png with random string!

2025-01-10 11:39 UTC, Martchus commented
> @Martchus I've done a copy paste of https://github.com/os-autoinst/os-autoinst/blob/master/t/misc_needles/click-point.png so it is already a symlink, but anyway it points to the json file

Ah, then the view on GitHub fooled me. I guess as a symlink it is kind of ok (and I introduced this kind of symlink). So you can keep it.

2025-01-10 11:40 UTC, Martchus approved these changes

2025-01-10 11:42 UTC, perlpunk commented on t/01-test_needle.t
> +    print "@$result\n";
```suggestion
```

2025-01-10 11:55 UTC, perlpunk approved these changes

2025-01-10 12:10 UTC, Wabri commented
I didn't understand why code coverage fail even if the coverage is 100%, I've rebased with master to check if is something related to it

2025-01-10 14:48 UTC, okurz approved these changes
Looks like codecov has some old data or is incorporating the pre-state for fully covered? You can try to exclude the codecov.yml changes from this PR and we can try to bring it in in another PR

2025-01-10 16:32 UTC, perlpunk commented on needle.pm
> -sub save ($self, $fn = $self->{file}) {
I would just use `YAML::PP::DumpFile('file.yaml', $needle)` if I wanted to debug the content into a file...

2025-01-10 17:45 UTC, merged

2025-01-10 17:48 UTC, okurz commented
Now https://app.codecov.io/gh/os-autoinst/os-autoinst/blob/master/needle.pm shows what looks still missing even though that looks different than the patch report in this PR

2025-01-13 08:55 UTC, Wabri commented
Why it didn't show previously? neither locally nor remotely? Working on it!