Add unit test for 'ensure_installed' to improve code coverage
os-autoinst/os-autoinst pull request #2605
Opened 2024-12-26 10:34 UTC by gauravpathak

- Rectified wait_still_screen call in distribution.pm to resolve error: `Undefined subroutine &distribution::wait_still_screen`
- Added even number of arguments in testapi::send_key to resolve perl warning: `Odd number of elements in hash assignment`

2024-12-26 11:39 UTC, okurz requested changes

2024-12-26 11:39 UTC, okurz commented on t/03-testapi.t
> +    );
Seems like you are not doing anyting with the mocked functions so probably just a "noop" will be enough

```suggestion
    $mock_testapi->noop('x11_start_program', 'wait_still_screen');
```

2024-12-26 11:39 UTC, okurz commented on t/03-testapi.t
> +    $mock_testapi->unmock_all;
that's not necessary as the mocked methods disappear when the variable `$mock_testapi` leaves scope

```suggestion
```

2024-12-26 11:49 UTC, okurz reviewed
Now please squash the commits

2024-12-26 11:51 UTC, gauravpathak commented
> Now please squash the commits

Done

2024-12-26 11:57 UTC, okurz approved these changes

2024-12-30 11:58 UTC, Wabri approved these changes

2024-12-30 11:58 UTC, merged

2025-01-06 11:45 UTC, perlpunk commented on distribution.pm
> +    if ($testapi::password) { testapi::type_password; testapi::send_key("ret", 1, 0); }
The arguments `1, 0` for `send_key` don't really have any purpose.
I assume this function hasn't been used for very long and the usage for `send_key` has changed in the meantime.
aae0b1623036bddeb8831f34126aef9e170b50e5 looks like that.
So I suggest to remove the additional arguments completely.

2025-01-06 11:46 UTC, perlpunk commented
What's the ticket for this PR? Please get in the habit of adding it to commit messages and PR descriptions, otherwise it's more work for me now to dig for it in redmine.

2025-01-06 13:08 UTC, gauravpathak commented
Sure, I will add the ticket for future Pull requests.

2025-01-06 13:10 UTC, gauravpathak commented on distribution.pm
> +    if ($testapi::password) { testapi::type_password; testapi::send_key("ret", 1, 0); }
Sure, will remove the additional arguments.
But I remember, I was getting some error that's why I added the additional argument

2025-01-07 10:11 UTC, gauravpathak commented on distribution.pm
> +    if ($testapi::password) { testapi::type_password; testapi::send_key("ret", 1, 0); }
I tried removing the extra argument, and got this error:
`Odd number of elements in hash assignment at os-autoinst/os-autoinst/testapi.pm line 1280`
```
ok 71 - ensure_installed test
not ok 72 - no (unexpected) warnings (via done_testing)

#   Failed test 'no (unexpected) warnings (via done_testing)'
#   at t/03-testapi.t line 1299.
# Got the following unexpected warnings:
#   1: Odd number of elements in hash assignment at /home/gaurav/Documents/GitHub-Repos/os-autoinst/os-autoinst/testapi.pm line 1280.
#   2: Odd number of elements in hash assignment at /home/gaurav/Documents/GitHub-Repos/os-autoinst/os-autoinst/testapi.pm line 1280.
1..72

```

2025-01-07 10:56 UTC, perlpunk commented on distribution.pm
> +    if ($testapi::password) { testapi::type_password; testapi::send_key("ret", 1, 0); }
My suggestion was to remove the **two** arguments `1, 0`. So that you would end up only with the key to send as an argument:
```suggestion
    if ($testapi::password) { testapi::type_password; testapi::send_key("ret"); }
```
If you look at the commit I referenced above, the second argument was removed from the send_key api.